### ISSUE TITLE
KBART field "coverage_depth" not shown and set automatically

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#1]
At the moment, the KBART field "coverage_depth" is not shown and cannot edited in the GOKb UI under "TIPP Details" bzw. "Coverage". It is automatically set to "Fulltext" when a TIPP is created. Regarding KBART specification, it could have three values "fulltext", "selected articles" and "abstracts". This field should be shown and be editable with these three Refdata Values.

**Comment by hornmo** [comment]
Fixed on g3_master in b8324e017bbd81bb9ddf56ef144487ddc3ef9abb
