### ISSUE TITLE
Current TIPPs for deleted TitleInstances

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#105]
It is somehow irritating that there are current TIPPs for TitleInstances marked as deleted. I would like to know how this is possible. Example: https://gokb.org/gokb/resource/show/63588ce2-ba47-48ba-ae2f-9f235b6b3e74#availability
In the very package are many such examples.

**Comment by darupp** [comment]
Should we implement autochanges for TIPP status when the title status is changed? How deep? Should this work also with de-deleting / re-activating a title? 

Correspending question is what a normal user can edit on title level. Suggestion: Editing is okay, deleting is forbidden.

**Comment by croqueGrec09** [comment]
What is the current state of this issue? It would be very interesting for sync questions ...

**Comment by croqueGrec09** [comment]
Alright; when can I expect a PROD deploy of this bugfix?

**Comment by hornmo** [comment]
The fix was merged in 8.5.1 and should therefore already be deployed.
