### ISSUE TITLE
Add fields in Api

### ISSUE THREAD

**Issue by Moetez16** [openlibraryenvironment/gokb#108]
Currently listVerifiedDate, scope, contentType is not displayed in the api as fields. Is needed for laser.

Thx.

**Comment by VolkerHBZ** [comment]
In which API request(s) you want to get those values?

**Comment by croqueGrec09** [comment]
We need the field in every call, generally. Should not be distincted.

**Comment by darupp** [comment]
These are package fields, so it is about the OAI package API. 

Correction: It is about the Elastic Search Interface

**Comment by hornmo** [comment]
Added in #141
