### ISSUE TITLE
KBART Export from GOKb - faulty fields

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#109]
The KBART Export from GOKb has some faulty field: 

  * *publication_type* has to be "serial" or "monograph" according to KBART II specification. Right now the GOKb export KBART file has "journal" and "book" instead. This should be changed according to the specification. The GOKb classes "journal" and "database" should be matched to "serial", "book" to "monograph". 

  * The UID should be exportet too, either as own field *gokb_uid* or as *title_id*, or see below

  * *title_id* gives at the moment the internal database id of the title instance. This is needless. This field could instead be used in two possibilities: 1) UID or 2) the vendor id. 2) could be problematic because there are different namespaces and it is not clear what to do if there are multiple vendor ids. I'd prefer GOKb  UID.

Suggestions?

**Comment by darupp** [comment]
UID: In additional fields: *gokb_tipp_uid* and *gokb_title_uid*

Vendor ID: Should be *title_id*, but then the vendor ID should be attached to tipp instead of title. This would a greater refactoring. So this part is on the Ice Box.

**Comment by hornmo** [comment]
Added in 336b6e0
