### ISSUE TITLE
Wrong title type after initial mirroring

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#110]
Because of a mismatch in initial sync process, title instances have been incorrectly mapped. About 600 titles which were book titles became journal titles that way. We have to consider what happens when an instance type gets changed afterwards.

Issues arising:
- notification of consuming systems (such as LAS:eR)

**Comment by croqueGrec09** [comment]
File with diff attached below:
[laser_gokb_title_type_diff_20191202.txt](https://github.com/openlibraryenvironment/gokb/files/3911969/laser_gokb_title_type_diff_20191202.txt)

**Comment by darupp** [comment]
These titles have to be deleted, because there is already data lost like first_author, first_editor, publication_date etc.

We need a list with the corresponding packages.

**Comment by croqueGrec09** [comment]
Updated file with diff attached below:

[https://app.zenhub.com/files/103426961/ac7d6d5c-84ac-440a-b85d-74ebe48c4076/download](https://app.zenhub.com/files/103426961/ac7d6d5c-84ac-440a-b85d-74ebe48c4076/download)
