### ISSUE TITLE
OAI-PMH coverage statement discrepancy

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#117]
The issue is as follows. Occurred in dev.

I first create the following package in GOKb with the following TIPP:
https://phaeton-dev.hbz-nrw.de/gokb/resource/show/org.gokb.cred.TitleInstancePackagePlatform:2179657#tippcoverage

I then have a coverage depth field on TIPP level which is set to Fulltext. An OAI-PMH-request to the very package reveals then a coverage element (with only attribute coverageDepth = Fulltext) in the extract. That element does not appear in the coverage statement list since it is - correctly - never created.

Then, I delete the depth attribute on TIPP level. Making the request reveals no coverage element.

Now, I create correctly, a CoverageStatement element and set there a startDate. Making then the OAI-PMH request reveals still no element.

**Comment by croqueGrec09** [comment]
The issue gets even more critical since the last coverage statement of a TIPP does not get deleted in LAS:eR as there is still a coverage statement in the OAI extract!

**Comment by hornmo** [comment]
Related to #210

**Comment by hornmo** [comment]
Fixed in #212
