### ISSUE TITLE
Main Menu: Log in user with username and password

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#118]
### Input
username, String
password, String

### Output
Token or empty response

### Implementation
```
POST /login
{  username: ‘Frank’,  password: ‘asdfkjl’}

Response
{ 
  access_token: "dsfsdf"
  token_type: "Bearer"
  username: "frank"
}
```

After logged in every following request has to use the given token and therefore is not further mentioned.

Almost done, I think.

**Comment by VolkerHBZ** [comment]
deployed for testing at https://phaeton-dev.hbz-nrw.de/gokb/rest/login

not merged onto g3_master yet.

**Comment by dirk-ecker** [comment]
Actual implementation gives this result:

access_token: "nki156f2o2aqsvnqno6r7ggjsvir3o9t"
roles: ["ROLE_CONTRIBUTOR", "ROLE_EDITOR", "ROLE_USER"]
token_type: "Bearer"
username: "decker"

refresh_token and expires_in is missing.

**Comment by VolkerHBZ** [comment]
refresh_token and expires_in is not supported, since the access_tokens don't expire in this token store implementation.

**Comment by dirk-ecker** [comment]
Okay, but a few days/or weeks ago those fields where available.
What has changed since then?

**Comment by dirk-ecker** [comment]
Okay, no problem. I change my implementation - it is also easier to handle for me.

**Comment by VolkerHBZ** [comment]
There are different token store implementations to choose from. the former had unlimited lifetime for refreshTokens and expiring accessTokens, but no logout. The current one supports logout but doesn't expire the accessTokens. Hence there's no use for refreshTokens.

**Comment by dirk-ecker** [comment]
Strange, logout and refresh token makes sense IHMO and we use it also in our other API.

**Comment by dirk-ecker** [comment]
Log In is working
