### ISSUE TITLE
Main Menu: Log out

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#119]
### Input
Token

### Output
Empty response

### Implementation
`POST /logout`

**Comment by VolkerHBZ** [comment]
deployed for testing at https://phaeton-dev.hbz-nrw.de/gokb/rest/logout
Header param:
Authorization: Bearer <access_token>

after logging out, requests using the access-token shall return 401 Unauthorized

not merged onto g3_master yet.

**Comment by dirk-ecker** [comment]
Actual implementation does not work, the serivce is not available.

**Comment by dirk-ecker** [comment]
It works.

**Comment by dirk-ecker** [comment]
Adds not needed Cookie to the response: JSESSIONID

**Comment by VolkerHBZ** [comment]
The Session Cookie could be responsible for the server-side error of data being accessible after logout still.

**Comment by dirk-ecker** [comment]
Ah, he is not really logging out.

**Comment by dirk-ecker** [comment]
Works as expected
