### ISSUE TITLE
Main Menu: Register a user

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#120]
### Description
Register a new user for the GOKb

### Input
username, String
email, string
password, String

### Output
Empty response or error details.

### Implementation
```
POST /register
{ 
  username: ‘Frank’,
  email: ‘frank@web.de’,
  password: ‘asdfkjl’
}
```

Response
empty or

```
{ 
  error: {
    id: "reg-001",
    message: 'username already registered',
    detail: 'The given username ....'
  }
}
```

**Comment by VolkerHBZ** [comment]
Not implemented because of the risk of possible abuse and DOS.

Register your new account via the old HTML interface.

**Comment by dirk-ecker** [comment]
We could implement it with reCAPTCHA I think:
https://developers.google.com/recaptcha
https://www.codeproject.com/Articles/116250/Custom-reCaptcha-Validation

What do you think @darupp ?

**Comment by dirk-ecker** [comment]
register gives me a 401
it should work without login

**Comment by VolkerHBZ** [comment]
Sorry, the implementation got not merged to the master, as the forementioned security concerns received deeper consideration.
