### ISSUE TITLE
View Profile: Delete the user profile

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#123]
### Description
After logging in the user can switch to his profile. Because of the token that is send to the server, we do not need a profile id to delete the profile.

### Implementation
`DELETE /profile
`
Error or empty response.

#### Actual Workload:

**Comment by VolkerHBZ** [comment]
@darupp What's the status after this endpoint has been triggered? Has the user been completely wiped from the database? Or is the account just set to be inactive? If so, how can the user control the final deletion of his data?

**Comment by dirk-ecker** [comment]
> @darupp What's the status after this endpoint has been triggered? Has the user been completely wiped from the database? Or is the account just set to be inactive? If so, how can the user control the final deletion of his data?

We already discussed the question, I think. The account is set inactive and can not be used to log in, all private data must be erased e-mail and the like.

**Comment by VolkerHBZ** [comment]
deployed in Ver 8.5.1

**Comment by dirk-ecker** [comment]
Checked dev with https://phaeton-dev.hbz-nrw.de/gokb/rest/profile that gives me
an empty JSON: {}

A 200 does it, you can remove the {}
