### ISSUE TITLE
View User: Get available roles

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#124]
### Description
The users dialog contains a select input for all available roles, that has to be filled.

### Implementation
```
GET /roles?_include=id,name&_exclude=_links&_sort=name&_order=asc

{
  data: [{
    id: 42,
    name: "Editor"
  }]
}

```

**Comment by dirk-ecker** [comment]
yes it gives you result, but these are provided not as the other types, with authority instead of name and written uppercase with dashes

**Comment by VolkerHBZ** [comment]
There is no name property in the Role Domain Object Class. And it's value is just like that: uppercase with dashes. The only way of changing this is in the Database, as the number of roles is not fixed and a translation table in the code has to be expanded when new roles emerge.
![Roles](https://user-images.githubusercontent.com/48286407/80732066-14059500-8b0c-11ea-97db-1415a4720448.png)
