### ISSUE TITLE
View User: Get available states

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#126]
### Description
The users dialog contains a select input for all available status, that has to be filled.

### Implementation
```
GET /states?_include=id,name&_exclude=_links&_sort=name&_order=asc

{
  data: [{
    id: 42,
    name: "Deleted"
  }]
}

```
#### Actual Workload:

**Comment by dirk-ecker** [comment]
the current implementation does not fit

**Comment by VolkerHBZ** [comment]
Actually, there is no implementation of that endpoint. This whole status stuff makes no sense in application to users, as user states are not represented by numbers but boolean values such as isAdmin, passwordExpired, accountExpired, accountLocked etc.
