### ISSUE TITLE
View Add/Edit User: Get available organisations

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#127]
### Description
The users dialog contains a select input for all available organisations, that has to be filled.

### Implementation
```
GET /organisations?_include=id,name&_exclude=_links&_sort=name&_order=asc

{
  data: [{
    id: 42,
    name: "HBZ"
  }]
}

```
We have to check the amount of organisations available. If there are more than a few, it makes sense to implement a searchable select input that causes the need for a paging api for organisations. The general rule should be to support paging for all resources.

#### Actual Workload:

**Comment by VolkerHBZ** [comment]
implemented as:
GET /rest/orgs
returns a paginated list of the available organisations

**Comment by dirk-ecker** [comment]
Could we move to /rest/organisations as requested? Using abbreviations is uncommon and not homogenous.

**Comment by VolkerHBZ** [comment]
speaking of homogenous: in the current application, the Organizations are mapped to domain object class Org. I think, we should stick with that scheme.

**Comment by dirk-ecker** [comment]
homogenous has something to do with equable build or consistent and means consistent on the same level. So at this point you can compare org to provider, user, ... and not to an entity on another layer - in this case the model layer. The 8 bit area is long over, where we try to shorten everything, nowadays the rule is to help the reader understanding the code and the like not to disinform him or her. And the time to change this to organisations is, I think, less than to argue about this thing again and again - otherwise the development environment is nicely said bad.

**Comment by hornmo** [comment]
I don't see a big problem changing the endpoint, though we should probably stick with `organizations`  since that spelling is a bit more agnostic concerning usage in different regions (US vs GB). The short form was used in the first place to mitigate those spelling issues, but the resulting term is not really speaking for itself.

**Comment by dirk-ecker** [comment]
Good idea.
