### ISSUE TITLE
View Users: Search users

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#128]
### Description
Search user with : name, role, curatory group or status.

#### Input
name, String,
roleId, Number,
curatory group id, curatoryId, Number,
status statusId, Number,
paging, offset and limit, Number,

sorting, asc or desc, String

#### Output
List of users with paging and name an email from user.

### Implementation

```
GET /users ?name=’frank’ &roleId=42 &curatoryGroupId=42 &statusId=42 &_include=name, email &_sort=name,email &_order=asc, desc &offset=10&limit=10

{ 
  data: [
    {
      id: 42, 
      name: ‘Frank’,
      email: ‘frank@gmail.com’,
      _links: {
        self: { href: ‘/users/42’ },
        update: { href: ‘/users/42’ }
      }
    },...  ],
    _pagination: {
      offset : 10
      limit: 10,
      total : 26
    },
    _links: {
      self: { href: ‘/users?name=’frank’&roleId=42&...&offset=10&limit=10’’ },
      first: { href: ‘/users?name=’frank’&roleId=42&...&offset=0&limit=10’ },
      last: { href: ‘/users?name=’frank’&roleId=42&...&offset=20&limit=10’ },
      prev : { href: ‘/users?name=’frank’&roleId=42&...&offset=0&limit=10’ },
      next: { href: ‘/users?name=’frank’&roleId=42&...&offset=20&limit=10’ }
  }
}

```
The self link can be used to edit a specific user, update can be used to change the user, in this dialog the user can be deactivated.

Like always no link available, no right to do it.

#### Actual Workload:

**Comment by VolkerHBZ** [comment]
changed endpoint to users/search for simplicity and to distinguish from the /users/{id} endpoint

**Comment by dirk-ecker** [comment]
is this technically driven

**Comment by dirk-ecker** [comment]
we should create a usual rest api that is homegenous that means with no suprise for the user

**Comment by VolkerHBZ** [comment]
OK

**Comment by dirk-ecker** [comment]
if possible

**Comment by dirk-ecker** [comment]
endpoint says 403

**Comment by dirk-ecker** [comment]
searching by Gruppen still not possible (tested on phaeton-dev):
GET /rest/users?curatory=62898

also GET /rest/users?role=4 and GET /rest/users?enabled=true

**Comment by VolkerHBZ** [comment]
the correct parameter names are: curatoryGroupId, roleId and status with status being a boolean value that indicates whether a user is allowed to use the system (status=true) or not (status=false) with no status given, all users will be returned.

**Comment by dirk-ecker** [comment]
thank you for the hints
