### ISSUE TITLE
View User: Deactivate user

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#129]
### Description
Use the update link and send a PATCH with active = false to deactivate a user.

### Implementation
```
PATCH /users/42
{ 
  active: true,
}

```
Typically the response contains the patched resouce, the user.

#### Actual Workload:

**Comment by VolkerHBZ** [comment]
Implemented as using the attribute enabled instead of active and with a data container in the request for consistency with other parts of the API

```
PATCH /users/42
{ 
  data: {
    enabled: false
  }
}
