### ISSUE TITLE
View User: Add/Update user

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#130]
### Description
After editing the user fields, the administrator could update the user using the save button, so we have to use a PUT request to update the data in the backend. In case of creating a new user we use the POST request with the same data.

#### Example for Update
```
PUT /users/42
{
  data: {
    name: ‘Frank’,
    password: ‘asdfkjl’,
    passwordExpired: true,
    email: ‘frank@gmail.com’,
    active: true,
    locked: false,
    roleIds: [42, 33],
    curatoryGroupIds: [42, 21]
  }
}
```

#### Example for Create
```
POST /users
{
  data: {
    name: ‘Frank’,
    password: ‘asdfkjl’,
    passwordExpired: true,
    email: ‘frank@gmail.com’,
    active: true,
    locked: false,
    roleIds: [42, 33],
    curatoryGroupIds: [42, 21]
  }
}
```

Both should return the created/updated entity.

**Comment by VolkerHBZ** [comment]
separate endpoint for editing user profiles
/profile works only for the authenticated user, changing his own profile.

**Comment by dirk-ecker** [comment]
POST /rest/users
accountLocked: true
email: "111@dd.de"
enabled: true
password: "1111"
passwordExpired: true
roles: [1]
username: "1111"

creates only a empty user with no data

**Comment by VolkerHBZ** [comment]
da fehlt das umgebende data:{...} Element im JSON. Die Daten kommen nicht im Controller an und darum wird ein leerer User angelegt und zurückgegeben.
