### ISSUE TITLE
View Add/Edit User: Get user

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#131]
### Description
Editing a given user needs a service to get its data:
- username
- password
- password expired
- email
- active
- locked
- organisation
- roles
- curatory groups

So we need a GET:

```
GET /users/42?_embed=organisations, curatorGroups

{ 
  data: {
    id: 42,
    name: ‘Frank’,
    passwordExpired: true,
    email: ‘frank@gmail.com’,
    active: true,
    locked: false,
    organisationId: 42,
    roleIds: [{ id: 42, name: ‘Contributor’ }, { id: 33, name: ‘Editor’ }],
    curatoryGroups: [{ id: 42, name: ‘LASeR’ }, ... ],
    _links: {
      self:  { href: ‘/users/42’’ },
      update: { href: ‘/users/42’ },
    }
  }
}

```
The existence of an update link in the result tells the frontend whether an update is allowed or not.

#### Actual Workload:

**Comment by dirk-ecker** [comment]
I always get a 404, not found. Maybe my guess of an id is to bad, but the id of my profile does also not work: https://phaeton-dev.hbz-nrw.de/gokb/rest/users/1859007.

What am I doing wrong?

**Comment by VolkerHBZ** [comment]
nothing.

The implementation of the user endpoint is on another branch (mine), than the one that's deployed (Moritz'), therefore, it's not online yet on phaeton-dev. 

Sorry 'bout that.
