### ISSUE TITLE
Curatory Group Changes 

### ISSUE THREAD

**Issue by MiriKon** [openlibraryenvironment/gokb#140]
I have noticed that when a curatory group is deleted in the GOKb packages, those changes are not automatically reflected in LAS:eR in ALL PACKAGES. 

![Sync_GOKb_LASER_2](https://user-images.githubusercontent.com/45172978/73437032-e6158680-434b-11ea-8481-ac7f8caad940.JPG)
![Sync_GOKb_LASER_1](https://user-images.githubusercontent.com/45172978/73437033-e6158680-434b-11ea-9d91-6f7372740892.JPG)

It seems that changes made for the curatory groups do not automatically trigger a "last updated" - it would be necessary, however, that changes within the curatory groups trigger such an update. Otherwise, the information regarding the packages in LAS:eR would be outdated and of little use because it is not a reliable information.

**Comment by croqueGrec09** [comment]
ex LAS:eR Ticket #2122
I strongly support the issue and suggest general extension to every other dependent object type since it is somewhat annoying to not seeing updates done on dependent objects just because the main object needs to be updated. This was the case with TIPPs as well before that was changed. And there may be more than one consumer of the GOKb-ES-Api.

**Comment by croqueGrec09** [comment]
See https://phaeton.hbz-nrw.de/gokb/oai/packages?verb=getRecord&metadataPrefix=gokb&identifier=65e67457-c48f-43f0-8489-f18cecb4d3bb
It seems that the inner-GOKb-Sync (so the mirroring) is not considering curatory groups ...

**Comment by croqueGrec09** [comment]
For the moment, the OAI endpoint for CuratoryGroups is not specified so that a transmission of curatory group changes is not possible right now. This is needed to be implemented.

**Comment by hornmo** [comment]
> It seems that the inner-GOKb-Sync (so the mirroring) is not considering curatory groups ...

> It seems that changes made for the curatory groups do not automatically trigger a "last updated"

Fixed in v8.5.0 (#141 ). Both systems need to be running the new version for this to work, and the latest version of sync scripts has to be used.

**Comment by croqueGrec09** [comment]
When can we expect a deploy of 8.5.0?

**Comment by hornmo** [comment]
Gokb.org is already running on 8.5.0, phaeton should be following shorty I imagine.
