### ISSUE TITLE
View Profile: Update the user profile

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#142]
### Description
After editing the profile data, the user can persist them.

### Implementation
```
PATCH /profile

{
  data: {
    email: ‘frank@gmail.com’,
    curatoryGroups: [42],
    password: ‘asdfkjl’,
    new_password: 'kjkldjlk'
  }
}

```
The given password has to be checked against the current password.
It should return the updated entity back to the caller.

**Comment by dirk-ecker** [comment]
at this time I only get 404 for PATCH and 500 for PUT

**Comment by dirk-ecker** [comment]
we also should switch to PATCH because most of the time we will not change everything, I think and that is the meaning of PUT

**Comment by VolkerHBZ** [comment]
PUT as well as PATCH are implemented... maybe some issue with merging.
