### ISSUE TITLE
Main Menu: Global Search

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#143]
### Description
The global search at the top of the main view needs a REST-Endpoint that searches among all Entities of type package, publisher, journal ... that contains the given title/name.

### Implementation
```
GET /entities?name=’physics’&offset=10&limit=10

{ 
  data: [
    {
      type: 'journal , package, publisher or ...',
      name: 'the name used for the view',
    },...  ],
    _pagination: {
      offset : 10
      limit: 10,
      total : 55
    },
    _links: {
      self: { href: ‘/entities?name=’physics’&offset=10&limit=10’ },
      first: { href: ‘/entities?name=’physics’&offset=0&limit=10’ },
      last: { href: ‘/entities?name=’physics’&offset=50&limit=10’ },
      prev : { href: ‘/entities?name=’physics’&offset=0&limit=10’ },
      next: { href: ‘/entities?name=’physics’&offset=20&limit=10’ }
  }
}
```

We should discuss the ordering/grouping of the results. What makes sense?

#### Actual Workload:

**Comment by VolkerHBZ** [comment]
The result comes grouped in chunks of size *limit*. Ordering by some sort of natural order (alphanumerically) makes sense, changing that order in a paginated list seems pretty much useless to me.

**Comment by hornmo** [comment]
Results will be retrieved via Elasticsearch and would therefore be ordered by relevance score (unless otherwise specified).

**Comment by hornmo** [comment]
Currently the parameter `name` does a lookup for whole words only, whereas `suggest` does a truncated search.
