### ISSUE TITLE
View Maintenance: Get available creators

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#144]
### Description
The maintenance dialog contains a select input for all available creators, that has to be filled.
(Fachkonzept_Erfassungsclient, p. 69)

### Implementation
```
GET /creators?_include=id,name&_exclude=_links&_sort=name&_order=asc

{
  data: [{
    id: 42,
    name: "?"
  }]
}

```
To discuss: Maybe the concept wants a list of users at this point, a service we already have.

#### Actual Workload:

**Comment by VolkerHBZ** [comment]
Closed for being the same as #128
