### ISSUE TITLE
View Create Title: Add/Update a title (was: Review? or Create a title)

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#146]
It is not explained what the button at the bottom should trigger.
(p. 52)

My guess ist, that the title is made persistent and put into the next process stage, called review. So this button simply creates the title with state "to be reviewed".

This is a bad UI. I think we should rename the button to Aktualisieren or Speichern. When the user selects a reviewer it is marked as to be reviewed otherwise not.

**Comment by darupp** [comment]
We should not contextualise the button at the bottom, so the button should be "Aktualisieren" or "Speichern" (as usual)

**Comment by dirk-ecker** [comment]
like in #130

**Comment by hornmo** [comment]
Added in #250 
Endpoint: POST `/titles?type=<journal|book|database>`

Separate endpoints (`/journals`, `/books`, `/databases`) for different types added in ae4b6ca01743f45fd77d636cdf4237d6915c5d8b
