### ISSUE TITLE
View Create Title: Get User (was: Get Reviewer)

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#150]
What are Reviewers? What is the name of the entity? Users?
(p. 52)

**Comment by hornmo** [comment]
Reviewers are Users linked in the field `allocatedTo` of a ReviewRequest. Those in turn will be connected to the title itself via a one-to-many association. This function will generate a new ReviewRequest allocated to a User with an optional note.

**Comment by dirk-ecker** [comment]
So a reviewer is a user - I changed the title.

**Comment by dirk-ecker** [comment]
like #126
