### ISSUE TITLE
View Title History: Splitting/Merging Titles

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#155]
It is mentioned that titles could be splitted or merged, but not how this can be accomplished.

(p. 55)

**Comment by darupp** [comment]
The splitting and merging is done via the buttons "Vorgänger" and "Nachfolger" that open the modal dialogue (p. 56). Regarding the data, this is defined by a title history event with 
  * set of predecessor title references
  * set of successor title references
  * event date

https://laser-qa.hbz-nrw.de/box/gokb-dbschema/tables/component_history_event.html
