### ISSUE TITLE
View Title History: Get title history

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#156]
### Description
The view has to show the title history for a title, so the Endpoint title should give us this.
(p.55)

### Implementation
```
GET /title/42?_include=history

{
  data: {
    history: [
      { since: '2010-01-01', ... }
    ]
  }
}
```

#### Actual Workload:

**Comment by hornmo** [comment]
Added in #250 
Endpoint(s): `/titles/<id>/history` or `/titles/<id>?_include=history` or `/titles/<id>?_embed=history`
