### ISSUE TITLE
View Create Package: Search provider

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#159]
### Description
The create package dialog contains a select input for all available provider, that has to be filled.

### Implementation
```
GET /provider?_include=id,name&_exclude=_links&_sort=name&_order=asc

{
  data: [{
    id: 42,
    name: "Springer"
  }]
}

```

**Comment by dirk-ecker** [comment]
GET /rest/provider?name=whatyouwant gives a 404

**Comment by VolkerHBZ** [comment]
I get a 500 - which is different, but wrong as well.

**Comment by VolkerHBZ** [comment]
as a workaround, i suggest to use the additional parameter es=true in order to lookup the components via ElasticSearch rather than using the hibernate implementation which seems flawed (hence the 500 error).

**Comment by dirk-ecker** [comment]
yes now 500
the problem could lie in the lack of _include parameter, because with _include it works
