### ISSUE TITLE
View Create Package: Add/Update package

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#162]
### Description
In step 4 of creating a package we need a service to store everything.
service. (p.43)

### Implementation
```
POST /package
{
  data: {
   ...
  }
}
```

Should return the created entity.

**Comment by darupp** [comment]
Should be package header incl. ids, provider, alternate names etc., but _without_ tipps.

**Comment by dirk-ecker** [comment]
Actual has errors and is not complete.

**Comment by VolkerHBZ** [comment]
what errors?
