### ISSUE TITLE
View Create Provider: Reference?

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#169]
It is not specified what this should be?
(p. 59)

**Comment by darupp** [comment]
Provider should be a top level menu item "Create provider" on the left hand menu and analogue to "Create package" and "create title". There is some inconsistency in the concept (p. 59) right now regarding the labels "organisation" and "provider". For now, we should stick with "provider" and discuss the correct term later.

**Comment by darupp** [comment]
Needs to be discussed. This seems to be legacy from the old GOKb. "On hold" for now. @hornmo, do you think we can ignore this field? I see no real need for it.

**Comment by hornmo** [comment]
Yes, this field has never really been used.
