### ISSUE TITLE
View Edit Provider: Missing requirement

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#170]
It is not described how we can get there.
(p. 60)

**Comment by darupp** [comment]
As this doesn't fit in the workflow where you can create a provider, if not found, via the second step in "create package" (See p. 35/p. 59), we need an extra workflow here.

Provider should be a top level menu item "Provider" on the left hand menu and analogue to "package" and "tilte", from where you can 
  * search a provider
  * edit a provider as on p. 59

**Comment by dirk-ecker** [comment]
New menu item 'Provider' added.

![image](https://user-images.githubusercontent.com/35012374/74024106-69b12200-49a1-11ea-8d4b-39b0fd5ee2df.png)
