### ISSUE TITLE
TitleHistory: TitleInstances pointing to deleted instances

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#171]
There are a display error and a connection error.

The title Czechoslovak journal of physics is connected to The European physical journal D. There are two instances of The European physical journal D: one of them is deleted and one of them is current.

When listing the TitleHistory, we see TitleHistoryEvents concerning both. That is somewhat very irritating. The OAI PMH extract delivers -correctly- only those linked directly to the database instance.

It is thus desired that upon deleting a title (or marking it as such), every links ponting from or to it should be remapped or deleted as well.

**Comment by hornmo** [comment]
Fixed in 8.5.1
