### ISSUE TITLE
View Dashboard: Get reviews

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#189]
### Description
Search reviews with type and creator for displaying table entries with name, type, created at, created from. (p.51)

#### Input
type, String,
creator, Number,
paging, offset and limit, Number,

sorting, asc or desc, String

#### Output
List of reviews with paging and name an ...

### Implementation

```
GET /reviews?type=’Paket’&creator=42&_include=name, type,createdAt, createdFrom &_sort=name&_order=asc&offset=0&limit=10
...
```

#### Actual Workload:

**Comment by hornmo** [comment]
Added in #251

**Comment by dirk-ecker** [comment]
Hi, I need some hints about the possible search parameters.
Thanks in advance.

**Comment by dirk-ecker** [comment]
Searching reviews is still not working, maybe because of unknown parameters that can be used.
I need searching by curatoryGroup, component, allocatedTo, raisedBy, state and name - the expexted do not work.

Also, according to specify the component I need a service to request all possible component types - should I create another ticket for that?
