### ISSUE TITLE
View Packages: Get identifier

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#193]
### Description
The users dialog contains a select input for all available identifiers, that has to be filled.

### Implementation
```
GET /identifiers?_include=id,name&_exclude=_links&_sort=name&_order=asc

{
  data: [{
    id: 42,
    name: "ISBN"
  }]
}

```

**Comment by hornmo** [comment]
Can you give me the context of this requirement? I'm not sure if this should be identifier values or namespaces, as suggested by the value "ISBN".

**Comment by dirk-ecker** [comment]
It's almost everywhere. Yes it's a bit more complicated. We need the possible types of identifiers and also their values.

**Comment by hornmo** [comment]
PR #251 introduced `/identifier-namespaces` for searching for namespaces like "isbn".
In addition, existing identifier objects may be looked up (for conflict detection) via  `/identifiers?value=<id_value>&namespace=<ns_value|ns_id>`.
