### ISSUE TITLE
View Packages: Get providers

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#194]

**Comment by VolkerHBZ** [comment]
Since providers are organizations, this issue is handled by the /rest/orgs endpoint.
`GET /rest/orgs?name=can`

**Comment by dirk-ecker** [comment]
Why are providers organizations? Is there no difference? Why do we have different namings for the same thing?

**Comment by hornmo** [comment]
The term `organizations` (or more specifically `Orgs`) is the object class used in the back-end to generalize the objects which are used for example as `publisher` for titles or `provider` for packages. To enable abstraction from this layer, besides the generic endpoint `/orgs` the API also offers `/provider` and `/publisher`, which are all mapped to the same controller function.

**Comment by VolkerHBZ** [comment]
sorry, my bad. I didn't realize you defined those endpoints as well.
