### ISSUE TITLE
UUID mismatch on nominalProvider record

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#197]
Comapre these two OAI records of the same package:

https://phaeton.hbz-nrw.de/gokb/oai/packages?verb=GetRecord&metadataPrefix=gokb&identifier=1b1ae804-343a-4854-9a5a-4e78e3e309eb

vs.

https://gokb.org/gokb/oai/packages?verb=GetRecord&metadataPrefix=gokb&identifier=1b1ae804-343a-4854-9a5a-4e78e3e309eb

Nominal provider's names are matching but the UUIDs do not. This causes LAS:eR to miss updates on nominalProvider.

**Comment by hornmo** [comment]
Fixed in 8.5.3
