### ISSUE TITLE
View Create Package: Add identifier

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#199]
### Description
If the user wants to add a new identifier using the modal dialog, we need a corrsponding REST service. (p.35)

### Implemenation
```
POST /identifier
{
  data: {
    type: ‘’,
    value: ‘’,
  }
}
```

Should return the created entity.

**Comment by dirk-ecker** [comment]
There has to be done a little bit more, I think, because it will be more like an identifier type and identifier values, we have to support.

**Comment by hornmo** [comment]
Identifiers are only created in the context of another component (eg package, title etc.). For this context, see for example #162.

**Comment by dirk-ecker** [comment]
Due to https://github.com/openlibraryenvironment/gokb-ui/issues/4#issue-613260292

**Comment by VolkerHBZ** [comment]
creating an identifier is implemented as follows
```
POST /rest/identifiers
{value: "someString", namespace: namespaceID}
```
Namespaces can be obtained via
```
GET /rest/identifier-namespaces
```
