### ISSUE TITLE
Stronger editing and deleting permissions

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#206]
As open knowledge base, the goal of the GOKb is to work cooperatively on its content. To prevent edit wars, there is a weak permission system regarding curatory groups, so if you want to change packages that are not curated by your group, you get a warning message that can be overridden.

As the prevention of edit wars for certain packages and as a mean of trust for data users who are getting back to a curatory group if the package is not correct, this warning message should be replaced with a stronger permission management.

So if there is a curatory group set for a record, no other editor should be able to edit the record.

**Comment by darupp** [comment]
Implemented in the REST Controllers for new GUI. Should also be integrated for package and tipps in the old UI.

**Comment by hornmo** [comment]
Added for next version.
