### ISSUE TITLE
View Seach Packages: Support Identifier

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#219]
The image on page 49 shows an input field for identifier, the description is missing.
Do we support identifier?

**Comment by hornmo** [comment]
Yes, Packages should be able to be linked to identifiers.

**Comment by dirk-ecker** [comment]
No, that is not the question. Should it be possible to search packages by identifier?
 
![image](https://user-images.githubusercontent.com/35012374/77642779-80660500-6f5e-11ea-9e09-d9c1749b3bbb.png)

**Comment by darupp** [comment]
In my opinion absolutely, as we get more and more package identifiers of different namespaces. 
Regarding a search field, an identifier should be searched regardless of the namespace, so a search term like "ZDB-55-120" would suffice to find all packages that have this identifier in one of their used identifier namespaces.

**Comment by hornmo** [comment]
Search by values via `?ids=<value>` added in #223

**Comment by dirk-ecker** [comment]
> Search by values via `?ids=<value>` added in #223
can you give me an example, i.e. I can`t find anything for zb

**Comment by VolkerHBZ** [comment]
/rest/orgs/598 returns the organisation with id=598

**Comment by hornmo** [comment]
Example on phaeton-dev:

https://phaeton-dev.hbz-nrw.de/gokb/rest/packages?ids=ZDB-47-CBA

Returns one package for an Identifier with namespace "isil".
