### ISSUE TITLE
Package export does not process book info

### ISSUE THREAD

**Issue by hornmo** [openlibraryenvironment/gokb#22]
All current package TSV export functions in PackageController & WorkflowController do not output any Monograph fields.

This should probably be fixed in concordance with #8.

**Comment by croqueGrec09** [comment]
To have the reference, I shall reference here own test results:
Tested on dev & QA
With reference to LAS:eR-tickets ERMS-1203 and ERMS-1150

When exporting EBook-packages (KBart and GOKb), no identifiers are being exported.
Tested with:

- dev: https://phaeton-dev.hbz-nrw.de/gokb/public/packageContent/org.gokb.cred.Package%3A812354
- qa: https://phaeton-qa.hbz-nrw.de/gokb/public/packageContent/org.gokb.cred.Package%3A812408

**Comment by hornmo** [comment]
Fixed in #49
