### ISSUE TITLE
View Search Packages: GOKb-Format/KBART-Format not specified

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#220]
It is a formal specification needed to implement the export in GOKb-Format/KBART-Format.

**Comment by darupp** [comment]
You can find the specification linked here: https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=470024321

- The first link leads to the official KBART documentation
- At the bottom of the table, you find proprietary extensions of the GOKb

**Comment by dirk-ecker** [comment]
Thanks for the link.
The filename format should be 

[ProviderName]_[Region/Consortium]_[PackageName]_[YYYY-MM-DD].txt

but in the near future we will have the possibility to choose more than one provider. Consortium means the same as curatory group? Where to get the PackageName? Do we need a dialog to specify these parameters?

In other words, what should the format be?

**Comment by darupp** [comment]
There will still be only one provider per package, see pp. 35/36 or pp. 49/50. The export files are always package specific. If in the list on p. 49 more than one package is picked, there should be multiple KBART and GOKb files exported (maybe in a ZIP). 

All String fields in the table should be normalized regarding the KBART title to fit the filename format (All blanks should be underscores, no forbidden characters etc.).

The [ProviderName] should be the name of the provider shown in the list on p.  ( @hornmo and I thought about using an short provider alternate name tagged as abbreviation. What do you think, @hornmo?)

The [PackageName] should be the name in the shown list.

The [Region/Consortium] is right now per convention part of the [PackageName], so there ist now further specification needed. 

I don't think a dialog is needed.

**Comment by hornmo** [comment]
There are existing public endpoints for exporting Packages which can be used:

KBART: <gokb-url>/packages/kbart/<uuid|OID>
GOKb-Format: <gokb-url>/packages/packageTSVExport/<uuid|OID>

These Endpoints return *.tsv files. We are planning to improve the parameter handling to also work with the database id.

**Comment by dirk-ecker** [comment]
Okay, good point. We should use these, instead of creating new one, I think.

**Comment by dirk-ecker** [comment]
Nice.
I've tested the following url

https://gokbt.gbv.de/gokb/packages/kbart/6196e907-59df-4cfd-94f6-91dd1e72b0b0

It gives me a 403 and Invalid CORS request.

Can you adjust the service to accept my request?

We should extend the service so that it can handle a query to specify the packages to export.

@darupp At least we need a select to choose the format KBART or GOKb and also a progress indicator.

**Comment by hornmo** [comment]
Wouldn't it be okay to just generate and display those links in the UI?

**Comment by dirk-ecker** [comment]
Thats a question for @darupp but I think not realy, cause the user want to download. You do not want to manually download those files by hand.

**Comment by darupp** [comment]
@dirk-ecker You're right, a dialogue and a progrss tracker would help here greatly.

**Comment by dirk-ecker** [comment]
In the first version we will support export for a single selection, means only one package.

**Comment by VolkerHBZ** [comment]
when I used a download link for the last time, I had to acknowledge a dialog for the download to start and then I got a nice tracker, showing me a progress bar as the download is running. It's possible to clone that standard behavior of any browser I know of, though, I'd question the necessity to do so.
