### ISSUE TITLE
OAI-PMH extract for TIPPs not delivering platformProviders

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#227]
When syncing package data, notably via the ListRecords endpoint, TIPP Platform stubs deliver name and UUID but no provider data. So the only way to update a platform's provider data is if it is indicated as a nominalProvider's provided platform. I would therefor suggest that the platform stub delivers a provider's UUID in order to update that as well.

**Comment by croqueGrec09** [comment]
There is a platform endpoint, it would be necessary to update the OAI endpoint listing (/gokb/oai) and documentation to all currently available endpoints

**Comment by hornmo** [comment]
Fixed in #257
