### ISSUE TITLE
platform provider not synced

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#228]
Tested with these records:

https://gokb.org/gokb/resource/show/c84d8db3-598f-48bf-9890-423b84900505
vs.
https://phaeton.hbz-nrw.de/gokb/resource/show/c84d8db3-598f-48bf-9890-423b84900505

In gokb.org record, provider is indicated whereas not in phaeton. The gokb.org record was touched and sync was obviously taking place but no provider data has been transmitted.

**Comment by croqueGrec09** [comment]
Comparing these two records:
https://gokb.org/gokb/resource/show/46eeea35-64fd-4dea-ac43-0d215b264b05
vs.
https://phaeton.hbz-nrw.de/gokb/resource/show/46eeea35-64fd-4dea-ac43-0d215b264b05,
the primary URL is missing in phaeton record.

**Comment by croqueGrec09** [comment]
The provider data is also missing for the following package. Comapre these two record:
https://gokb.org/gokb/public/packageContent/c6e8d1b7-b59b-48ed-80e0-458ca2dbdd9c
vs.
https://phaeton.hbz-nrw.de/gokb/public/packageContent/c6e8d1b7-b59b-48ed-80e0-458ca2dbdd9c

**Comment by hornmo** [comment]
Fixed in 8.6.4.
