### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by philboeselager** [openlibraryenvironment/gokb#244]
- I try to login with my credentials as they have always been
- I get an error message: "Invalid username or password"
- I choose "Forgot password?" and follow the instructions: I click the link in the mail and re-set the password. For this moment, I am logged in.
- I log out
- I log in with my username and the new password
- I get the error message: "Invalid username or password" again

DOD: Having re-set a password, the error message does not occur again.

EDIT: occured on phaeton-dev

**Comment by VolkerHBZ** [comment]
your account "boeselager" is not enabled. This might be the reason, why you cannot log on. The error seems to be the fact that you were logged in to the system through the reset-password-process even though your account is disabled.

I have set the account to enabled - that should enable you to log on again.

**Comment by philboeselager** [comment]
I'm able to log in again. Thanks for solving. Closing.
