### ISSUE TITLE
user test3 is not allowed to change property curatoryGroupIds of user test3

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#261]
PATCH /rest/profile
{email: "abc@ded.de", new_password: "t", curatoryGroupIds: [752573]}

throws 400

also the old password is not given and therefore it should regret the change of it.

**Comment by VolkerHBZ** [comment]
the request is semantically wrong, rejected with a 400 response code and therefore the data stays unchanged.
Although I was hoping for the client to prevent requests from missing fields.

**Comment by dirk-ecker** [comment]
It depends on the user. User test3 has not the needed privileges, I think.
