### ISSUE TITLE
static interface for reporting errors

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#263]
The interface of the error response depends on the error type or the number of errors or ...?

I got a response where errors is an array of object and on the other hand I got a response where errors is an object.

It should always be the same interface. If only one error has occurred we should also return an array of errors. Its bad practice to "optimize" this way, because it makes the handling more complicated on both sides of the API.

**Comment by VolkerHBZ** [comment]
as mentioned in https://github.com/openlibraryenvironment/gokb/issues/262, the array of errors is a bug: errors is a map of property names to error objects. Along with the implementation in other parts of the GOKb, an error object consists of a message and some baddata. To localize the message, an additional code is delivered to look up an appropriate text.
