### ISSUE TITLE
View Add Title: Dialog variants?

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#266]
Adding a title by hand can be done for a book, a database, a journal, a monograph and a series.
All of these different title types actual gets the same ui fields, but that can not be correct. So we need further specification what is needed in the type context,  see page 39.

**Comment by VolkerHBZ** [comment]
journal and serial are just different names for the same type - JournalInstance, book and monogaph too: BookInstance, database points to a DatabaseInstance. They all are subclasses of TitleInstance. 
The UI fields you are referring to (Ausgaben, Bände) are actually properties of the TIPPCoverageStatement, not the TitleInstance itself. The dialog mixes up data from the TitleInstance and its three-way-relation to package and platform. 
IMHO it's more sensible to create platform and package first and after the title is created, it can be linked with packages and platforms along with the specific coverage within a package and a platform.

**Comment by dirk-ecker** [comment]
The question is which input fields are relevant for what. We need different gui prototypes.

**Comment by dirk-ecker** [comment]
Further investigation into the old ui shows more input fields than the actual concepts offers. But it shows also the differences between the known title types. I have created a [word document ](https://fz-juelich.sciebo.de/s/UfMm1keNVPhGPsI) that shows the results and can be used to discuss this topic in detail.

**Comment by VolkerHBZ** [comment]
Is there a way to add remarks and comments to that document? Maybe a DAV-link to edit it offsite?

**Comment by VolkerHBZ** [comment]
Unfortunately, it's impossible to add comments to that document.

**Comment by dirk-ecker** [comment]
Simply download and edit.

**Comment by VolkerHBZ** [comment]
Instead of typing around in a copy, I'd rather want to edit the real thing so you can read and react to the comments, as this is key to a discussion, don't you think?

**Comment by dirk-ecker** [comment]
This is sciebo and I think you have no account, so we must/should share it via email or deploy it elsewhere. Try this

https://drive.google.com/file/d/141zfnaUogl8OYM1Y_59eFS83nezYBfUv/view?usp=sharing

**Comment by VolkerHBZ** [comment]
Same problem: without an account, no editing.

But: as employee of HBZ, I can setup a sciebo-account on my own... hope this will enable me to work on that document... fingers crossed.

The document seems to be read-only. Probably a rather suboptimal way of starting a discussion - except you are Recep Tayyip Erdoğan, which you're not.
