### ISSUE TITLE
incorrect output of non-latin characters

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#269]
The following KBART file contains a record with a cyrillic title. Even after having corrected the record to the name to Письмо, what Ygor processes correctly, it is incorrectly transmitted to GOKb and incorrectly stored. It should thus be necessary to check whether all the interserver connections and all the database connections are consequently UTF-8.
Occurred on GOKb 8.6.0 with Ygor v0.92.

[hbz.ava.watch_26 May 2020_kbart.txt](https://github.com/openlibraryenvironment/gokb/files/4831647/hbz.ava.watch_26.May.2020_kbart.txt)

**Comment by hornmo** [comment]
This seems to be an issue with [Ygor](https://github.com/hbz/laser-ygor/), since I was not able to reproduce this issue when sending the title to GOKb directly via the Crossreferencing API.

**Comment by croqueGrec09** [comment]
@philboeselager @hornmo Can it be a communication issue between the servers?

**Comment by hornmo** [comment]
@croqueGrec09 I don't think so. The Problem seems to be present in the exported JSON from YGOR already.

**Comment by croqueGrec09** [comment]
I did the test again with a manually corrected (this is important to stress) KBART file which is going to be included here. Ygor version 0.92. The titles JSON is correct as is the output in Ygor.
[hbz.ava.watch_26 May 2020_kbart.txt](https://github.com/openlibraryenvironment/gokb/files/4836686/hbz.ava.watch_26.May.2020_kbart.txt)

**Comment by croqueGrec09** [comment]
After title cleanup / deletion of faulty title and reupload, the title was rendered correctly. Closed.
