### ISSUE TITLE
Title mismatch Apollo

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#273]
Given the TitleInstance https://gokb.org/gokb/resource/show/org.gokb.cred.BookInstance%3A6241061#titledetails.
In fact, it should be two title instances given the same name because it occurs in https://gokb.org/gokb/resource/show/org.gokb.cred.Package%3A11751449 and in https://gokb.org/gokb/resource/show/org.gokb.cred.Package%3A6243109. In former, it is a film title and in latter, it is an eBook. We are thus talking about two different title instances what has the consequence that film titles get ISBNs.

**Comment by hornmo** [comment]
No. Items from KBART can only be separated via their `publication_type`, namely `serial` or `monograph`. Those values directly correlate with a specific Item type in the GOKb (BookInstance/JournalInstance). The value of `medium` can then be used to further differentiate the titles, but will not be used for matching of future imports. So unless the titles contain differing global identifiers (so both would need a different `doi` in effect), I am afraid your use case  cannot be reflected properly by the KBART standard and you should therefore refrain from misusing it in this manner.

**Comment by croqueGrec09** [comment]
The matter of this ticket is that two independent records are reflected into one.

**Comment by hornmo** [comment]
This is because only one of the titles has any reliable identifiers, and both are classified as a BookInstance. Titles without proper identifiers cannot be matched properly, and are therefore prone to cause such errors. The safest solution would be to refuse any titles without proper (globally recognized) identifiers, but that would have to be discussed further.

**Comment by croqueGrec09** [comment]
Alright, should thus become subject of discussion.

**Comment by philboeselager** [comment]
Given the fact that countless examples of matching books & films titles exist, we need to make this work.

@hornmo : What is the minimum criteria to make two titles distinguishable in this case?

My assumption: if there is a duplicate title, check the medium type.

- If the medium types are different, check identifiers.
  - If identifiers are different: OK --> create both items independently
  - If there is a duplicate identifiers: --> create a Review Request
- If the medium types are the same, we can not defer a case descibed here. So the procedure must be kept as is.

**Comment by hornmo** [comment]
Yes, that sounds correct. I was going to completely ignore other types of titles in the identifier lookup, but creating a review request could probably be helpful for such cases.

**Comment by philboeselager** [comment]
@hornmo Is this fixed within the two PRs mentioned above? If so, please close this issue.

**Comment by hornmo** [comment]
Those PRs fixed this issue.
