### ISSUE TITLE
Medientyp "Sonstiges/Various"

### ISSUE THREAD

**Issue by MiriKon** [openlibraryenvironment/gokb#277]
Um neben den bisherigen Publication Types "monograph" und "serial" noch Medientypen in die GOKb einspielen zu können, die keiner dieser Kategorien zugeordnet werden können (Branchenreports, Film- und Musiktitel etc.), sollte im Feld publication_type noch die Kategorie "various" hinzugefügt werden und dieser Typ in der GOKb integriert werden wie auch von Ygor beim Einspielen der KBART-Datei akzeptiert werden. 

Zwingend notwendige Spalten wären für diesen Typ vorerst:

1. publication_title
2. title_url
3. title_id

**Comment by hornmo** [comment]
Die GOKb verarbeitet bereits den Wert "Other" für generische Titeldatensätze. Falls es keine starke Präferenz für "various" gibt, wäre dieser zu bervorzugen.

**Comment by MiriKon** [comment]
Das es tatsächlich schon einen Wert in der GOKb gibt, war mir gar nicht bewusst. Dann nehmen wir auch "other" - da gibt es keine Präferenz von unserer Seite :-)

**Comment by philboeselager** [comment]
@hornmo Sind damit GOKb-seitig alle Vorkehrungen getroffen? D. h. ich brauche Ygor-seitig nur noch die Angabe `Other` (bzw. `other`) zu ermöglichen, und alles läuft?

**Comment by hornmo** [comment]
@philboeselager Korrekt, das sollte schon funktionieren.

**Comment by philboeselager** [comment]
@hornmo Please deploy Ygor on gokb.org.
