### ISSUE TITLE
Anlegen Namespace

### ISSUE THREAD

**Issue by MiriKon** [openlibraryenvironment/gokb#278]
Beim Anlegen eines Namespaces für einen Anbieter wird in der GOKb momentan außer dem Namen immer noch das Feld "Category" mit dem Wert "ttl_prv" vergeben - hier die Frage welchen Zweck das Feld erfüllt und ob man auf diesen Eintrag nicht verzichten könnte, da eigentlich nur der Namespace Name wichtig wäre? Bzw. könnte das Eintragen des Namespaces nicht auch direkt beim Anlegen einer Organization als eigenes Feld (wie es z.B. auch die alternativen Namensformen sind) erfolgen? 

Bislang ist das extra Anlegen des Namespaces sehr umständlich und mit dem Category Wert nicht ganz nachvollziehbar, wozu dieser Wert eigentlich "dient".

**Comment by VolkerHBZ** [comment]
dazu kann ich nichts sagen, das wurde entschieden, bevor ich in das Projekt gekommen bin

**Comment by hornmo** [comment]
Wir benutzen die Kategorie, um in Ygor eine Auswahlliste mit zugelassenen Werten für den proprietären Identifikator (title_id) zu generieren. Dort soll natürlich explizit z.B. keine ISIL ausgewählt werden können, da diese keine Titel identifiziert. Der Wert "ttl_prv" ist meiner Meinung nach unglücklich, wurde aber damals als Anforderung von LAS:eR gewählt.

Die direkte Verknüpfung (am besten 1:1) zwischen Org & Namespace wäre meiner Meinung an sich auch wünschenswert, würde aber eine Erweiterung des Datenmodells voraussetzen. Mit dieser Lösung könnten wir die Auswahl dann in der Regel auf `doi`/`provider` reduzieren, was sich erst einmal sehr attraktiv anhört.

**Comment by philboeselager** [comment]
@hornmo : Da eine Unterscheidung zwischen proprietären und anderen Namespaces schon sinnvoll zu sein scheint, ist die Vergabe einer `category` ja prinzipiell richtig. Der Name `ttl_prv` ist freilich "geheimnisvoll"... 

- Können wir diesen Wert nachträglich in "proprietary" umbenennen? Wollen wir das tun? (Ich fänd es sinnvoll, bzw. vereinfachend. Bitte erwähne mich kurz in der Antwort, damit ich die Änderung in Ygor entsprechend nachziehen kann.)
- Ist es möglich, die Angabe einer `category` obligatorisch zu machen? In dem Fall bräuchten wir mindestens einen Gegenbegriff, also z. B. "non-proprietary".
- Die Liste von auswählbaren categories sollte vermutlich geschlossen sein, und nur bei begründetem Bedarf erweitert werden. Was meinst Du?
- Die Verknüpfung eines Namespace mit einem Provider (oder alternativ einer Plattform) wird allgemein für sinnvoll gehalten. Provider scheint dabei der naheliegendere Ankerpunkt zu sein. Bitte gib mir auch hier kurz über Änderungen Bescheid, damit ich in Ygor entsprechend nachimplementieren kann.

Insgesamt würde die Namespace-Pflege damit hoffentlich erleichtert werden, so dass sie langfristig von allen GOKb-Nutzer*innen durchgeführt werden kann.
