### ISSUE TITLE
Konzept für Nutzerregistrierung in der GOKb

### ISSUE THREAD

**Issue by MiriKon** [openlibraryenvironment/gokb#279]
Die komplette Nutzerregistrierung in der GOKb sollte einmal vor allem auch in Hinblick auf die DSGVO neu konzeptioniert werden. Das Ticket schon einmal als Anstoß, dass wir das auf dem Schirm und als To-Do haben.

**Comment by VolkerHBZ** [comment]
Da du dich offenbar bereits mit den Anforderungen der DSGVO auseinandergesetzt hast, kannst du sicher auch ein paar Anstöße geben, wo die GOKb mit der DSGVO kollidiert. Nach meiner Kenntnis sowohl der DSGVO wie auch der GOKb bestehen keine offensichtlichen Widersprüche, was gut ist, weil andernfalls der Betrieb der GOKb seit dem 25. Mai 2018 illegal wäre.

**Comment by MiriKon** [comment]
Hier wäre ein Konzept wichtig, wie das gesamte Zugangsmanagement in der GOKb entsprechend DSGVO-konform aussehen könnte. Die Idee wäre auch hier eher pro Kuratorengruppe einen Admin initial anzulegen, so dass sich der Kurator selber pflegen und weitere Nutzer für die eigene Gruppe erstellen kann. Wichtig wären auch in dem Zuge eine Art Teilnehmererklärung auch für die GOKb zu haben.

**Comment by darupp** [comment]
Die Anforderungen sind relativ klar und wir haben sie auch schon bei LAS:eR erfüllt. Zentral brauchen wir nur ein veröffentlichtes Verfahrensverzeichnis und Prozesse, um nicht genutzte Nutzerdaten zu löschen.

Aber, und das ist der entscheidende Punkt: Die Nutzerdaten für das Produktivsystem liegen nicht im hbz. Hierfür können wir kein Verfahrensverzeichnis schreiben. Relevant ist das lediglich für das QA-System, hier werde ich ein Verfahrensverzeichnis formulieren.

**Comment by darupp** [comment]
Dass die Nutzerverwaltung umkonzipiert werden soll, ist ein anderes Thema und ein eigenes Arbeitspaket.

**Comment by darupp** [comment]
In interne Diskussion verschoben: https://dienst-wiki.hbz-nrw.de/display/GDI/Konzept+Selbstverwaltung+Kuratorengruppen
