### ISSUE TITLE
"Technischer Support" für Organization

### ISSUE THREAD

**Issue by MiriKon** [openlibraryenvironment/gokb#280]
Gerade im Rahmen der Anbieter-gesteuerten Pflege in der GOKb ist es wichtig, dass es hier ein extra Feld gibt, wo der Anbieter auch die Mail-Adresse des Technischen Supports angeben kann - diese Information sollte dann wiederum auch künftig in LAS:eR angezeigt werden. GOKb-seitig habe ich hier einmal einen Screenshot gebastelt:
![Organization_TechnischerSupport](https://user-images.githubusercontent.com/45172978/86452997-6423f200-bd1d-11ea-973f-8c9cb7df6ebc.JPG)
In dem Rahmen wäre auch einmal zu überlegen was die bisherigen Felder aussagen sollen, die man bei der Organization befüllen kann - Relations, Custom Fields und Offices. Das wäre zwar erst einmal zweitrangig, aber schon mal etwas für den Hinterkopf.

**Comment by VolkerHBZ** [comment]
![Bildschirmfoto vom 2020-07-03 12-22-36](https://user-images.githubusercontent.com/48286407/86460082-119c0300-bd28-11ea-8c06-cb437408247d.png)
das sieht mir nach einem klassischen Anwendungsfall für ein Custom Field aus. Die Datenstrukturen in der GOKb sind bewußt dynamisch gehalten, damit nicht für jede winzige Änderung ein neues Binary erforderlich wird.

**Comment by philboeselager** [comment]
@croqueGrec09 Ließe sich das Feld bei der von Volker beschriebenen dynamischen Befüllung für LAS:eR sinnvoll (parametrisiert) auslesen?

**Comment by croqueGrec09** [comment]
Man müsste hierzu die Struktur der Custom Fields exakt mit entsprechendem Parameter für den OAI-PMH-Auszug mitliefern. Hierzu wäre es hilfreich, wenn ich tatsächlich immer als Attribut "Technichal Support" (oder irgendeinen anderen festgelegten, instanzunabhängigen Begriff) erwarten könnte.

**Comment by croqueGrec09** [comment]
Zur Diskussion hier der Listenendpunkt für Orgs: https://gokb.org/gokb/oai/orgs?verb=ListRecords&metadataPrefix=gokb
Ich bräuchte jetzt irgendwo eine Struktur, dh.h entweder ein Element <customProperties> mit <customProperty type="technicalSupport">, wo sich LAS:eR das entsprechende Datum schnappen könnte.

**Comment by philboeselager** [comment]
OK, das klingt doch sinnvoll. Da die Properties der Custom Fields in einem Dropdown organisiert sind, sollte es gut möglich sein, hier immer den gleichen Feld-Identifier zu verwenden. Als Beispiel systemintern: `technicalSupport`. 

@MiriKon Ist diese Lösung aus fachlicher Sicht gut? Das heißt: ist die Angabe "prominent" genug? Leider kann nicht immer alles "ganz vorne" stehen, d. h. hier ist wirklich abzuwägen, wie wichtig die jeweilige Angabe ist.

@VolkerHBZ Wenn MiriKon das so absegnet, hast Du alles, was Du zur Implementierung brauchst, oder?

**Comment by MiriKon** [comment]
Ok, das wäre dann aus meiner Sicht eine ganz gute Lösung - dann könnte man perspektivisch das Feld "Custom Fields" auch nehmen, um neben dem technischen Support auch weitere relevante Ansprechpartner als fixen "Wert" zu hinterlegen. Dann sollte der Technical Support an der vorgeschlagenen Stelle so implementiert werden.

**Comment by VolkerHBZ** [comment]
est. duration: 3d

**Comment by MiriKon** [comment]
Das Hinterlegen des technischen Supports ist vor allem im Rahmen der angestrebten Automatisierung ziemlich wichtig - deshalb bitte priorisieren.

**Comment by VolkerHBZ** [comment]
real duration: 0d 
Ist bereits implementiert.

**Comment by philboeselager** [comment]
Wunderbar. Die Lösung dieses Issue's ist also, in der Edit-Maske der Organization der Reiter "Custom Fields" auszuwählen, und dort eine Property mit dem Schlüssel "Technical Support" (aus einem Dropdown) und dem gewünschten Kontakt anzulegen. 

@VolkerHBZ Ist die Property im OAI PMH Auszug dann ebenfalls unter `"Technical Support"` zu finden? Wenn ja, bitte schließe dieses Issue.

@MiriKon Wenn Du noch Konfigurationsfragen hast, kannst Du die weiterhin hier kommentieren.

**Comment by croqueGrec09** [comment]
@philboeselager Ja, ist es, vgl. https://phaeton-dev.hbz-nrw.de/gokb/oai/orgs?verb=GetRecord&metadataPrefix=gokb&identifier=org.gokb.cred.Org:42910

**Comment by VolkerHBZ** [comment]
als Anmerkung: der Auswahlwert "Technical Support" muss vor der Benutzung mittels `Create -> Additional Property Definition` angelegt werden.

**Comment by darupp** [comment]
Dublette mit https://github.com/openlibraryenvironment/gokb/issues/137

**Comment by MiriKon** [comment]
Der Eintrag mit "Technical Support" im Custom Field klappt leider nicht - hier muss der "Technical Support" noch in die Auswahlliste eingetragen werden.

P.S.: Wenn das Feld "Office" hier besser geeignet ist, dann da bitte das Eintragen des Technischen Supports möglich machen bzw. falls es schon möglich ist, bitte kurze Info wie es geht.

**Comment by darupp** [comment]
Wir benutzen vorerst das Feld "Technischer Support", weil das schon über die API ausgegeben wird. In der neuen Oberfläche können wir das über das Office machen. Für die neue Oberfläche muss ohnehin eine neue 

Ich habe als Admin in der Produktiv-GOKb das Custom Field angelegt über https://gokb.org/gokb/create/index?tmpl=org.gokb.cred.AdditionalPropertyDefinition.
