### ISSUE TITLE
View Edit User: Add organisation

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#282]
Regarding page 71 of the functional concept we need a organisation field in the user entity.

**Comment by philboeselager** [comment]
@dirk-ecker Is there any need for further discussion? If not, feel free to implement as you've written. (my guess)

**Comment by dirk-ecker** [comment]
I can`t find the field in the response and a PATCH gives me an error, so somebody at the database and REST level has to implement it.

**Comment by VolkerHBZ** [comment]
so far, users are only grouped into roles and curatory groups. apparently, there seems to be a newly discovered necessity for another membership in just another group. The simplest solution could be to define the curatory group with index 0 as the first and main organization of a user. Going this way, the implementation can advance without further waiting.

**Comment by dirk-ecker** [comment]
A curatory group is not an organisation - in the data model - or am I wrong.
I am not waiting, it is simply not used, when not set.

**Comment by VolkerHBZ** [comment]
Yes, you're right: a curatory group HAS zero or more orgs, rather than being one.

**Comment by hornmo** [comment]
There is a currently unused component called UserOrganisation, which may be used to group Users in another way to Curatory Groups. As it stands now, we don't have a clear concept how to use this, therefore user organisations should be omitted from the UI for now.

**Comment by VolkerHBZ** [comment]
Probably, this is the time to fill that unused property with some sense and define that UserOrganisation fits the need and use it accordingly.

**Comment by VolkerHBZ** [comment]
est. duration: 5d
