### ISSUE TITLE
View Titel: Embargo

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#284]
The field embargo of a title contains several details in one field: type, unit and duration. That is usually a bad practice because it adds complexity into development where it is not needed and we have no reason to save some bytes nowadays. So I suggest to split this field into three fields.

**Comment by VolkerHBZ** [comment]
this implementation follows the KBART standard (see [KBART_Phase_2_Dokumentation.pdf](https://github.com/openlibraryenvironment/gokb/files/4869762/KBART_Phase_2_Dokumentation.pdf) section 6.6.14) as well as the expectations from LAS:eR which uses exactly the same format. Changing the implementation only exagerrates complexity without adding any value.

**Comment by dirk-ecker** [comment]
code duplication by design

**Comment by philboeselager** [comment]
@dirk-ecker : As we've discussed today, you have already implemented the UI. Does this issue need something on the backend side? Otherwise, please close this issue.

**Comment by dirk-ecker** [comment]
You could use it to further improve the database. ;-)
but it is no problem for me to close it.
