### ISSUE TITLE
View Edit User: No 200 for errors

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#285]
Actually patching a user with an organisation id result into an error response but in the context of status = 200.
It should be a status <> 2xx.

**Comment by VolkerHBZ** [comment]
est. duration: 1d

**Comment by VolkerHBZ** [comment]
the 200 acknowledged the change of the properties that are correct and additionally telling that organisation is an unknown property that coudn't be processed. Changing the implementation so that the request is rejected altogether and giving a 400 return code.
