### ISSUE TITLE
View Add Title: Coverages service missing

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#286]
For filling the select box in the Add Title dialog I need a service to get all coverages values. The wiki describes these:
 * Abstracts
 * Fulltext
 * Selected Articles

**Comment by VolkerHBZ** [comment]
that's actually all there is and will be, but we stick with the pattern and'll craft an endpoint delivering these values.
something like:

GET /rest/coverageDepth

{"data": ["Abstracts", "Fulltext", "SelectedArticles"]}
est. duration: 1d

**Comment by dirk-ecker** [comment]
Pleas name it coverage-depth, thank you.

**Comment by VolkerHBZ** [comment]
Ok, done
