### ISSUE TITLE
View Provider: Selection of curatory group not supported?

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#287]
Selecting providers by curatory group does not give other result, so it seems that this query parameter is not supported yet.

**Comment by hornmo** [comment]
Please add the complete request that was used when the error occurred.

**Comment by dirk-ecker** [comment]
/rest/provider?curatoryGroupId=62898&_include=id,name&offset=0&limit=10

in contrast to

/rest/users?curatoryGroupId=415860&_include=id,username,email&offset=0&limit=10

that is working

**Comment by hornmo** [comment]
I'm afraid `/users` is different from all other endpoints in that regard. In general the request parameters will be the same as the property name returned in the response objects. So it should be

`/rest/provider?curatoryGroups=62898&_include=id,name&offset=0&limit=10`

I will add this format for users as well, so we'll be consistent throughout.

**Comment by dirk-ecker** [comment]
Okay, using the curatoryGroups it works.
