### ISSUE TITLE
View Provider: Selection of identifier should be improved

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#288]
At this time I use all possible identifiers to search for the input given by the user, but that makes no sense. It should be only identifiers that belongs to providers, I think. 

So we need a way to search for identifiers of a given entity by adding a new parameter for the rest endpoint identifiers - entity as string - or, I think the better alternative, support a method to find identifiers in the context of the entity i.e. /rest/providers/identifiers.

In contrast to /rest/providers/42/identifiers the request to /rest/providers/identifiers addresses all identifiers that belongs to providers.

**Comment by hornmo** [comment]
I don't think I fully understand this one. Can you specify possible request parameters as well as an example of a result payload you would expect?
