### ISSUE TITLE
View Provider: Retire or delete url not working

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#289]
The given retire and delete url due to an provider request seems not to be implemented or throws errors.

A POST to rest/orgs/2185774/retire gives an 404 and a DELETE to rest/orgs/2185774 gives an 500er.
Maybe I am doing something wrong.

The links were provided by rest/provider?name=test&_include=id,name&offset=0&limit=10

**Comment by dirk-ecker** [comment]
For the 500er I got an exception:

xception: {cause: null, localizedMessage: "No such property: pkg for class: org.gokb.rest.OrgController",…}
cause: null
localizedMessage: "No such property: pkg for class: org.gokb.rest.OrgController"
message: "No such property: pkg for class: org.gokb.rest.OrgController"
messageWithoutLocationText: "No such property: pkg for class: org.gokb.rest.OrgController"
module: null
node: null
property: "pkg"
stackTrace: [,…]
suppressed: []
type: "org.gokb.rest.OrgController"
message: "Server Error"

**Comment by VolkerHBZ** [comment]
is this bug resolved now?

**Comment by dirk-ecker** [comment]
Delete is resolved but gives a result not needed - maybe only in development environment.
Retire gives a 404.
