### ISSUE TITLE
View Dashboard: Request for actual running KBART Imports

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#293]
As specified on p. 51 we need a REST service that returns details about the actual running KBART Imports.

**Comment by VolkerHBZ** [comment]
est. duration: 5d

**Comment by philboeselager** [comment]
@hornmo Wouldn't we prefer to implement this on the Ygor side?

**Comment by VolkerHBZ** [comment]
In my view, Ygor is the only entity, that has knowledge about the imports. GOKb is only recieving single requests, but has no information about the original KBART-Upload that has triggered the requests.

.

**Comment by dirk-ecker** [comment]
That means we do not need this?
As a user, when you start something, like an upload, it would be nice to see if it is done or not.

**Comment by VolkerHBZ** [comment]
This is not what I have written. I support Philipp when he says that this information is only available in YGOR and any request asking for it has to be answered by YGOR. Either directly to YGOR or via an unspecified number of proxies. If I could choose, my approach would be to gather the information where it actually is..

**Comment by philboeselager** [comment]
@hornmo Would we still want that?
