### ISSUE TITLE
View Provider: GET Response not nested in data

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#296]
The response of getting a provider is not nested inside a data object analogue to the other services.

**Comment by VolkerHBZ** [comment]
est. duration: 1d

**Comment by VolkerHBZ** [comment]
For endpoints predictably returning a single object (i.e. a request with a supplied id), the client currently does not expect the response to contain a data container.

**Comment by VolkerHBZ** [comment]
For endpoints predictably returning a single object (i.e. a request with a supplied id), the client currently does not expect the response to contain a data container.
