### ISSUE TITLE
View Provider: Improve service to search for identifier

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#300]
Suggesting an identifier for searching a provider should be improved, so that only identifiers of providers are shown.
Therefore we need a parameter..

**Comment by VolkerHBZ** [comment]
Since there's no direct link from providers to identifiers, I suppose, you expect something like "return all identifiers of all publications by the given provider"!?

**Comment by dirk-ecker** [comment]
Yes that would it be I think. The reason to request this enhancement is to only get available ids, but I do not know the user intention. Does it makes sense?

**Comment by VolkerHBZ** [comment]
the endpoint /rest/identifier-namespaces now has a parameter to specify the type of namespaces to list:
`/rest/identifier-namespaces?targetType=<Org|Package|Title|Book|Journal|Database|Other>`
There is no special TargetType for Providers or Publishers, as they're all Orgs. If it's impossible to use only Org as parameter value in the request, the implementation can be broadened to map any other string to Org.

**Comment by dirk-ecker** [comment]
Okay, this tickets needs further improvements. During implementation I saw that you are talking about namespace and I instead mean identifier. I want to search for identifiers for a specific target type not for  namespaces. So it should be `/rest/identifier?...`.

By the way I found that the latter gives also the namespaces.
