### ISSUE TITLE
View Users: Added organisation is not saved.

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#304]
PATCH /rest/users/66870

accountLocked: false
curatoryGroupIds: [62903]
email: "Ciesielczyk@hebis.uni-frankfurt.de"
enabled: true
id: 66870
organisation: 44375
passwordExpired: false
roleIds: []
username: "HebisJC"

returns a 200 but shows error object in the result

errors: [{$field: {message: "unknown", baddata: "organisation", code: null}}]
0: {$field: {message: "unknown", baddata: "organisation", code: null}}
$field: {message: "unknown", baddata: "organisation", code: null}
baddata: "organisation"
code: null
message: "unknown"
result: "OK"

**Comment by VolkerHBZ** [comment]
won't fix until #282 is solved.
