### ISSUE TITLE
Non-telling baddata response

### ISSUE THREAD

**Issue by philboeselager** [openlibraryenvironment/gokb#311]
When uploading data to the GOKb, sometimes records are rejected and the message returned contains a large `baddata`-Objekt that is not telling anything really. Examples:

1 | {code=400, message=Title processing failed for title Documents de l'OCDE!, baddata={coverage=[{coverageDepth=Fulltext, startIssue=1, endDate=2008-09-05, endVolume=7, startVolume=1, endIssue=12, startDate=2001-04-25}], new_record=Yes, package={internalId=10685057}, subject=Economics, listprice_eur=12, language=fr, preceding_publication_title_id=10.1787/1995283x, title={identifiers=[{type=eissn, value=1684-341X}, {type=issn, value=1609-5316}], name=Documents de l'OCDE, type=Serial}, platform={name=OECD UN iLibrary, primaryUrl=https://www.un-ilibrary.org/}, url=http://dx.doi.org/10.1787/1684341x}}
-- | --
2 | {code=400, message=Title processing failed for title OECD Papers!, baddata={coverage=[{coverageDepth=Fulltext, startIssue=1, endDate=2008-09-05, endVolume=7, startVolume=1, endIssue=12, startDate=2001-04-25}], new_record=Yes, package={internalId=10685057}, subject=Economics, listprice_eur=13, language=en, preceding_publication_title_id=10.1787/1995283x, title={identifiers=[{type=eissn, value=1681-2328}, {type=issn, value=1609-1914}], name=OECD Papers, type=Serial}, platform={name=OECD UN iLibrary, primaryUrl=https://www.un-ilibrary.org/}, url=http://dx.doi.org/10.1787/16812328}}
3 | {code=400, message=Title processing failed for title Energy Prices and Taxes!, baddata={coverage=[{coverageDepth=Fulltext, startIssue=4, startVolume=1993, startDate=1994-01-17}], new_record=Yes, package={internalId=10685057}, subject=Energy, listprice_eur=17, language=en, title={identifiers=[{type=eissn, value=1609-6835}, {type=issn, value=0256-2332}], name=Energy Prices and Taxes, type=Serial}, platform={name=OECD UN iLibrary, primaryUrl=https://www.un-ilibrary.org/}, url=http://dx.doi.org/10.1787/16096835}}
4 | {code=400, message=Title processing failed for title OECD Journal on Budgeting!, baddata={coverage=[{coverageDepth=Fulltext, startIssue=1, startVolume=1, startDate=2001-03-26}], new_record=Yes, package={internalId=10685057}, subject=Governance, listprice_eur=21, language=en, title={identifiers=[{type=eissn, value=1681-2336}, {type=issn, value=1608-7143}], name=OECD Journal on Budgeting, type=Serial}, platform={name=OECD UN iLibrary, primaryUrl=https://www.un-ilibrary.org/}, url=http://dx.doi.org/10.1787/16812336}}
5 | {code=400, message=Title processing failed for title OECD Journal: Competition Law and Policy!, baddata={coverage=[{coverageDepth=Fulltext, startIssue=1, endDate=2011-06-22, endVolume=11, startVolume=1, endIssue=3, startDate=1999-02-04}], new_record=Yes, package={internalId=10685057}, subject=Governance, listprice_eur=30, 55, language=en, title={identifiers=[{type=eissn, value=1609-7521}, {type=issn, value=1560-7771}], name=OECD Journal: Competition Law and Policy, type=Serial}, platform={name=OECD UN iLibrary, primaryUrl=https://www.un-ilibrary.org/}, url=http://dx.doi.org/10.1787/16097521}}
6 | {code=400, message=Title processing failed for title OECD Economic Studies!, baddata={coverage=[{coverageDepth=Fulltext, startIssue=1, endDate=2007-09-06, endVolume=2006, startVolume=1994, endIssue=2, startDate=1994-11-15}], new_record=Yes, package={internalId=10685057}, subject=Economics, listprice_eur=30.55, language=en, preceding_publication_title_id=10.1787/19952856, title={identifiers=[{type=eissn, value=1609-7491}, {type=issn, value=0255-0822}], name=OECD Economic Studies, type=Serial}, platform={name=OECD UN iLibrary, primaryUrl=https://www.un-ilibrary.org/}, url=http://dx.doi.org/10.1787/16097491}}

This *package* upload response seems to be a follow-up of failing *title* uploads?!? 

The *titles* upload json is like (only faulty records):

	[{
	  "identifiers" : [ {
		"value" : "1684-341X",
		"type" : "eissn"
	  }, {
		"value" : "1609-5316",
		"type" : "issn"
	  } ],
	  "name" : "Documents de l'OCDE",
	  "type" : "Serial",
	  "publisher_history" : [ {
		"name" : "OECD Publishing"
	  } ],
	  "language" : "fr",
	  "listprice_eur" : "12",
	  "new_record" : "Yes",
	  "preceding_publication_title_id" : "10.1787/1995283x",
	  "subject" : "Economics"
	},{
	  "identifiers" : [ {
		"value" : "1681-2328",
		"type" : "eissn"
	  }, {
		"value" : "1609-1914",
		"type" : "issn"
	  } ],
	  "name" : "OECD Papers",
	  "type" : "Serial",
	  "publisher_history" : [ {
		"name" : "OECD Publishing"
	  } ],
	  "language" : "en",
	  "listprice_eur" : "13",
	  "new_record" : "Yes",
	  "preceding_publication_title_id" : "10.1787/1995283x",
	  "subject" : "Economics"
	},{
	  "identifiers" : [ {
		"value" : "1609-6835",
		"type" : "eissn"
	  }, {
		"value" : "0256-2332",
		"type" : "issn"
	  } ],
	  "name" : "Energy Prices and Taxes",
	  "type" : "Serial",
	  "publisher_history" : [ {
		"name" : "OECD Publishing"
	  } ],
	  "language" : "en",
	  "listprice_eur" : "17",
	  "new_record" : "Yes",
	  "subject" : "Energy"
	},{
	  "identifiers" : [ {
		"value" : "1681-2336",
		"type" : "eissn"
	  }, {
		"value" : "1608-7143",
		"type" : "issn"
	  } ],
	  "name" : "OECD Journal on Budgeting",
	  "type" : "Serial",
	  "publisher_history" : [ {
		"name" : "OECD Publishing"
	  } ],
	  "language" : "en",
	  "listprice_eur" : "21",
	  "new_record" : "Yes",
	  "subject" : "Governance"
	},{
	  "identifiers" : [ {
		"value" : "1609-7521",
		"type" : "eissn"
	  }, {
		"value" : "1560-7771",
		"type" : "issn"
	  } ],
	  "name" : "OECD Journal: Competition Law and Policy",
	  "type" : "Serial",
	  "publisher_history" : [ {
		"name" : "OECD Publishing"
	  } ],
	  "language" : "en",
	  "listprice_eur" : "30, 55",
	  "new_record" : "Yes",
	  "subject" : "Governance"
	},{
	  "identifiers" : [ {
		"value" : "1609-7491",
		"type" : "eissn"
	  }, {
		"value" : "0255-0822",
		"type" : "issn"
	  } ],
	  "name" : "OECD Economic Studies",
	  "type" : "Serial",
	  "publisher_history" : [ {
		"name" : "OECD Publishing"
	  } ],
	  "language" : "en",
	  "listprice_eur" : "30.55",
	  "new_record" : "Yes",
	  "preceding_publication_title_id" : "10.1787/19952856",
	  "subject" : "Economics"
	}]

**Comment by philboeselager** [comment]
The *package* Json.

[Uploading 20200811-1441-OECD_777_20_listprice.tsv.package.json.txt…]()

**Comment by philboeselager** [comment]
The KBart.
[OECD_777_20_listprice.txt](https://github.com/openlibraryenvironment/gokb/files/5057098/OECD_777_20_listprice.txt)

**Comment by philboeselager** [comment]
*Package* Json.
[20200811-1441-Miriam_OECD_777_20_listprice.tsv.package.json.txt](https://github.com/openlibraryenvironment/gokb/files/5057107/20200811-1441-Miriam_OECD_777_20_listprice.tsv.package.json.txt)

**Comment by VolkerHBZ** [comment]
any hints on how to reproduce that error?

**Comment by philboeselager** [comment]
> any hints on how to reproduce that error?

1. Upload titles json
2. Upload package json

Can be done by re-running Ygor or by using a REST-Tool with the Json-Files attached above.

**Comment by VolkerHBZ** [comment]
No errors when I try it.
![noErrors](https://user-images.githubusercontent.com/48286407/90388616-600f2200-e088-11ea-9efa-93ced13b524c.png)

**Comment by hornmo** [comment]
Fixed in #352
