### ISSUE TITLE
"RDF Datatype" lost when creating Identifier Namespace

### ISSUE THREAD

**Issue by philboeselager** [openlibraryenvironment/gokb#32]
Create --> 
Namespace -->
set `Name` and set `RDF Datatype` (to `string`) --> 
click `Create and Edit >>` --> 
the content of `RDF Datatype` is lost in the next view.

**Comment by philboeselager** [comment]
`RDF Datatype` is obviously never stored. See YOURFAVOURITEGOKBINSTANCE/search/index?qbe=g%3ANamespaces&offset=0&det=

**Comment by hornmo** [comment]
The CreateController has problems with setting RefdataValues with non-standard RefdataCategories, so whereas `{class.simpleName}:{property}` is fine, `RDFDataType` is not.
