### ISSUE TITLE
Keine Fehlermeldung bei YGOR, aber es werden nicht alle Titel in die GOKb eingespielt.

### ISSUE THREAD

**Issue by ChristinSeegert** [openlibraryenvironment/gokb#320]
Einspielung in PROD. 

Auf Seiten von YGOR gab es keine Fehlermeldung und alle Titel (7226) waren intakt. In der GOKb sind im Paket aber nur 6686 Titel angekommen.
![IBISWorld1GOKb](https://user-images.githubusercontent.com/70701502/93459993-e6ff2680-f8e2-11ea-8ac7-9bf6b228955d.png)
![IBISWorld1YGOR](https://user-images.githubusercontent.com/70701502/93459994-e8305380-f8e2-11ea-85a6-9d0fbcd3d3c6.png)
![IBISWorld2YGOR](https://user-images.githubusercontent.com/70701502/93459996-e8305380-f8e2-11ea-8bf8-1926ee0cb8af.png)

Anhänge:
[Ibisworld_Juli_2020_2.txt](https://github.com/openlibraryenvironment/gokb/files/5238467/Ibisworld_Juli_2020_2.txt)
[20200917-1314-Ibisworld_Juli_2020_2.txt.raw.zip](https://github.com/openlibraryenvironment/gokb/files/5238672/20200917-1314-Ibisworld_Juli_2020_2.txt.raw.zip)
[JSON.zip](https://github.com/openlibraryenvironment/gokb/files/5238764/JSON.zip)

**Comment by hornmo** [comment]
Nach erster Inspektion mit OpenRefine gibt es in der Datei 1211 Werte in 'title_id', die nicht eindeutig sind (teilweise bis zu 5 mal verwendet). Da dies der einzige verwertbare Identifikator der Datei ist, werden diese Titel jeweils gemergt. Manche dieser Titel haben unterschiedliche Namen, was zu den ReviewRequests 'Title was matched via secondary id, but had a different name.' führt, es gibt aber auch offensichtliche Dubletten. Gleichzeitig gibt es auch Titel mit unterschiedlichen IDs, aber dem gleichen Titel (was aber durchaus auch korrekt sein kann), wodurch der ReviewRequest 'No matched components via IDs, but a title with a similar name already exists.' erzeugt wird.

Die Meldung der GOKb ist insofern vielleicht etwas zu unspezifisch, da diese Zahl letztendlich die verarbeiteten Zeilen wiedergibt, nicht aber die endgültige neue Anzahl an aktuellen TIPPs.

**Comment by philboeselager** [comment]
@ChristinSeegert Die doppelten bzw. mehrfachen Einträge unterschieden sich im Länder-Kürzel in der `title_url`. Beispiele:

- World price of rubber
- World price of cotton
- World GDP

Ygor- und GOKb-seitig ist die Verarbeitung nach derzeitiger technischer Spezifikation korrekt.

Das Problem ist, dass die `title_url` bislang nicht Identifier-Funktion hat, wenn ich das richtig sehe.

**Comment by hornmo** [comment]
> Das Problem ist, dass die title_url bislang nicht Identifier-Funktion hat, wenn ich das richtig sehe.

Auf der Seite der GOKb werden TIPPs über die URL durchaus unterschieden. Daher gibt es hier auch Titel mit mehreren TIPPs in diesem Paket, z.B. https://gokb.org/gokb/resource/show/org.gokb.cred.OtherInstance:13305373#availability

**Comment by philboeselager** [comment]
> Auf der Seite der GOKb werden TIPPs über die URL durchaus unterschieden. Daher gibt es hier auch Titel mit mehreren TIPPs in diesem Paket, z.B. https://gokb.org/gokb/resource/show/org.gokb.cred.OtherInstance:13305373#availability

@hornmo Dann ist wiederum interessant, warum die Unterscheidung hier nicht passiert. Ygor merged die Zeilen ja nicht, wie man anhand der `package.json`-Datei sehen kann, und was sich auch anhand des Feedbacks der Anzahl der verarbeiteten Zeilen der GOKb zeigt.

**Comment by MiriKon** [comment]
Habe mir stichprobenartig die Dubletten jetzt auch einmal angeschaut und eigentlich wäre aus meiner Sicht nur wichtig, dass die Titel alle eine individuell ansteuerbare URL haben - was ja soweit ich es mir angeschaut habe, der Fall ist. Auch wenn sich die URLs nur minimal durch den Ländercode unterscheiden, sind es ja individuelle auf die Ressource führende URLs. Es scheint mir ein grundlegendes Problem zu sein, dass zu stark auf Identifier geschaut wird - die aus meiner Sicht zwar auch nicht unwichtig sind, aber vor allem für Medientypen wie bei IBISWorld eigentlich nur nice to have sind. Eigentlich sollte die title_url hier viel stärker in den Fokus rücken, wenn der Anbieter für seine Titel eine eindeutige direkte Zugriffs URL in der KBART Datei aufführt. 

Das Problem wird auch bei anderen KBART Dateien von Anbietern aufkommen, z.B. wenn die URL unterschiedliche Sprachvarianten des Titels abbildet. Oftmals bleibt dann aber die ID gleich. Wenn der Anbieter also für die unterschiedlichen Sprach- oder Länderversionen der Titel eine eigenständige URL hat, die individuell vom Nutzer angesteuert werden kann, wieso dann das nicht auch so in der GOKb abbilden?

**Comment by VolkerHBZ** [comment]
Letztlich kommt es auf die Definition an, die unserem Datenmodell zugrunde liegt. Darauf müssen die Daten, die geliefert werden, angepasst werden. Im vorliegenden Fall wurden Identifier mehrfach benutzt, was letztlich bedeutet, dass diese Identifier kein **hinreichendes** Merkmal sind, um zu entscheiden, ob zwei Titel identisch sind. Allerdings ist genau das die Voraussetzung, von der YGOR und die GOKB bisher ausgegangen sind. Ein Abweichen von dem Prinzip der Eindeutigkeit von Identifikatoren zieht das Problem nach sich, dass es in Zukunft schwierig sein könnte, eine Änderung an einem Titel zuzuordnen, wenn die ID meheren Titeln zugewiesen ist.
Im vorliegenden Fall scheint es mir so zu sein, dass tatsächlich **identische** Daten unter **verschiedenen** URLs erreichbar sind. Es ist also semantisch eher die Zuordnung eines Dokuments in verschiedene Kontexte. Ob wir diese potentiell uferlose Wiederholung gleicher Daten in unserem Katalog haben wollen und gleichzeitig auch einen Sack anderer Probleme (bei der Datenpflege) in unser System einbauen, ist nicht meine Entscheidung. Wenn man mich fragt, wäre ich allerdings dagegen, weil der Aufwand nicht unerheblich und die Probleme umfangreich sind, während der Nutzen bescheiden ist.

**Comment by VolkerHBZ** [comment]
unter den 7226 Datensätzen waren 4683, bei denen die title_id tatsächlich eineindeutig war. Hinzu kommen 1211 weitere Titel, deren Anzahl durch Wiederholung auf 2543 mehr als verdoppelt wurde.
Anbei alle 2563 Datensätze, deren title_id mehrfach benutzt wurde.
[Ibisworld_doubles.txt](https://github.com/openlibraryenvironment/gokb/files/5244279/Ibisworld_doubles.txt)

**Comment by darupp** [comment]
Wir werden das Problem in einer Sitzung besprechen und überlegen, wie wir eine praktikable Lösung finden.

**Comment by darupp** [comment]
Zusammengefast kommen folgende Fälle kommen in dem Paket vor: 

  1. Selbe ID, selber URL, selbe Name (512 Paare)
     --> Hier handelt es sich um eindeutige Dubletten. Die Zeilen der KBART-Datei sind 100% identisch. Hier muss der Anbieter ran. [IbisWorld_completeDoubles.txt](https://github.com/openlibraryenvironment/gokb/files/5245512/IbisWorld_completeDoubles.txt)
  2. Selbe ID, selbe URL, unterschiedliche Namen (12 Paare) 
     --> Werden fälschlich als ein einziger TIPPs zu einem Titel angelegt, was korrekt ist, wenn die ID tatsächlich eine Ressource mit mehreren Zugängen beschreibt. Problem der Namen muss gelöst werden. [IbisWorld_diffNames.txt](https://github.com/openlibraryenvironment/gokb/files/5245547/IbisWorld_diffNames.txt)
   3. Selbe ID, unterschiedliche URL, unterschiedliche Namen (97 Paare)
    --> Werden als mehrere TIPPs zu einem Titel angelegt, was korrekt ist, wenn die ID tatsächlich eine Ressource mit mehreren Zugängen beschreibt. Problem der Namen muss gelöst werden. [IbisWorld_strangeData.txt](https://github.com/openlibraryenvironment/gokb/files/5245563/IbisWorld_strangeData.txt)
  4. Selbe ID, unterschiedliche URL, selber Name 
    --> Werden korrekt als mehrere TIPPs zu einem Titel angelegt [IbisWorld_diffURL.txt](https://github.com/openlibraryenvironment/gokb/files/5245583/IbisWorld_diffURL.txt)

Verlust von TIPPs resultiert daher aus den Fällen 1 und 2 (Gleiche ID und gleiche URL, 524 IDs, davon 516 doppelt, 8 vierfach)
