### ISSUE TITLE
Integration API: Import von Medium

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#321]
Für die Title Ingegration API gibt es das Feld `medium`. Die Verarbeitung sollte wie folgt verbessert werden:

  * Die Vorbelegung eines nicht bekannten Wertes für `medium` sollte nicht mehr "Journal" sein, sondern abhängig von PublicationType: "Book" für "Monograph", "Journal" für "Serial", "Database" für "Database", leer für "Other". 
  * Bei einem falschen Wert (kein existierender Referenzwert) sollte der Titel angenommen, aber das Feld `medium` leer gelassen und ein Review Request erstellt werden.

Eine erweiterte Liste mit alten und neuen Refernzwerten ist angehängt: [folgt]

Korrespondierendes YGOR-Ticket: https://github.com/hbz/laser-ygor/issues/288

**Comment by croqueGrec09** [comment]
Aus Sicht ziehender Systeme wird es von die weitere Verarbeitung des Titeltyps sehr interessant sein.

**Comment by philboeselager** [comment]
Ist das nicht ein Ygor-Ticket? (Geht wahrscheinlich sowohl als auch.)

**Comment by darupp** [comment]
Das betrifft auch die GOKb, weil hier eine feste Liste mit Referenzwerten liegt. Für YGOR habe ich ein analoges Ticket erstellt. Ist jetzt oben verlinkt.

**Comment by VolkerHBZ** [comment]
aktuell ist diese Vorbelegung static in der Klasse TitelInstancew hinterlegt. Die komplexe Mechanik mit reviewRequest lässt sich sicher nicht mehr so einfach bauen. d.h. es wäre ein spezieller Setter für medium oder ein Methodenaufruf im Konstruktor.
@hornmo: comments?
