### ISSUE TITLE
Namespace: Erweiterung um (menschenlesbaren) Namen

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#324]
Erweiterung von Namespaces: 

Namensräume erhalten zusätzlich zum Feld "name" ein Freitextfeld für einen menschenlesbaren Namen (inkl. Leerzeichen und Groß-/Kleinschreibung). 

Der Name soll entsprechend in den APIs und Indizes ausgegeben werden (OAI und ES), siehe #323

**Comment by croqueGrec09** [comment]
Es wäre wünschenswert, wenn bei Implementierung im OAI-PMH-Auszug beide Namen ausgegeben werden, damit sie in nehmenden Systemen gematched und angepasst werden können.

**Comment by darupp** [comment]
Okay, wird berücksichtigt.

**Comment by VolkerHBZ** [comment]
Es gibt noch kein Feld 'name' in Namespace, wohl aber die Felder 'value' und 'family'. 
Ich implementiere einfach mal **ein** Feld 'name' und exportiere das. Nicht beschweren, dass es nur eins ist...

**Comment by darupp** [comment]
Okay, mehr brauchen wir auch nicht.
