### ISSUE TITLE
Automatisierung: Implementierung von Automatisierungsoptionen in der GUI

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#327]
Auf Paketebene sollen die notwendigen Daten für die Automatisierung in der Paketsicht bearbeitbar sein. 

  * GUI-Position: Im Paket-Bearbeitungsseite in Schritt 2 ("Verknüpfte Daten" - "Weitere Paketinfos")
  * Notwendige Daten zur Einspielung (Klasse Package oder Klasse Source)
    * URL für die Automatische Anreicherung
    * Update-Intervall in Tagen (default: 1, also täglich)
    * Grundeinstellungen YGOR
       * Namensraum für _title_id_ (Auswahl: Eigener, DOI,...)
       * (Anreicherungsschnittstellen) <- Auslassen, es wird zunächst ohne Anreicherung funktionieren müssen.

Die Daten müssen entsprechend beim `Package` auch über die APIs ausgeliefert werden (OAI-PMH und ES)

Hierzu gibt es ein entsprechendes YGOR-Ticket: https://github.com/hbz/laser-ygor/issues/294
Korrespondierendes GUI-Ticket: https://github.com/openlibraryenvironment/gokb-ui/issues/21

**Comment by VolkerHBZ** [comment]
Die GUI-Änderungen sollte vorzugsweise jemand machen, der sich mit diesem VUE.js auskennt.

**Comment by darupp** [comment]
Ich habe mal noch ein korrespondierendes gokb-ui-Ticket aufgemacht und Moritz zugewiesen.

**Comment by darupp** [comment]
Überlegungen zur Datenstruktur: 

Es gibt schon die Klasse `Source`, die diese (oder eine analoge) Funktion übernimmt. Hier können u.a. eine URL, ein Updateintervall, eine verantwortliche Organisation, eine Liefermethode (FTP, HTTP etc.) sowie ein Dateiformat (KBART, Proprietär) gespeichert werden. 

M.E. reicht diese Struktur nicht aus. Teilweise ist der Overhead zu groß, teilweise fehlen Details: 

  * Eine URL sollte immer paketspezifisch sein. Eine allgemeine URL ist nicht sinnvoll. Würden wir diese Klasse verwenden, bräuchten wir für jedes automatische Paket eine eigene `Source`.
  * Die verantwortliche Partei ist unnötig, da diese immer die Kuratorengruppe des Pakets sein sollte.
  * Automatisiert unterstützen wir lediglich ein Format (KBART) und eine Liefermethode (HTTP)

Daher schlage ich eine Integration in die Klasse `Package` vor, anstatt dieses Datenkonstrukt zu verwenden.

**Comment by darupp** [comment]
Nach Besprechung wird `Source` genutzt mit einer tatsächlichen 1:1-Beziehung zu `Package`. Dadurch ändert sich sinnvollerweise der Anwendungsfall von `Source`, da die ursprüngliche Funktion (Manuelle Übersicht über die Quellen) vermutlich irrelevant ist. 

In der Oberfläche ist die `Source` voll integriert in die `Package`-Sicht als eigenes Panel, d.h. der Nutzer merkt nicht, dass er an einem eigenen Objekt arbeitet. Die `Source` könnte angelegt werden, wenn man "Automatisches Update" anwählt.

Das Intervall wird nicht in Tagen, sondern wie `Embargo` umgesetzt, d.h. mit Optionen wie _täglich_ (d), _wöchentlich_ (w), _monatlich_ (m), _quartalsweise_ (q) und _jährlich_ (y). Dazu später eventuell Bezugstag für Intervall (Am 1. des Monats). 

Als URL nehmen wir das Feld `url`. Das Feld `responsibleParty` wird nicht genutzt.
