### ISSUE TITLE
Automatisierung: Persistierung der URL zur automatischen Anreicherung mit Platzhalter

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#328]
Zur Automatischen Anreicherung soll eine URL eingegeben werden können (siehe https://github.com/openlibraryenvironment/gokb/issues/327). Manche Anbieter verlinken direkt auf eine URL mit Dateinamen, die ein Datum in sich tragen, z.B. https://www.emeraldgrouppublishing.com/sites/default/files/2020-09/EmeraldPublishing_Global_EmeraldAccountingFinanceandEconomicseJournalCollection_2020-09-04.txt

Hier ist zu überlegen, wie die URL sinnvoll persistiert wird: Als Vorschlag: Es könnte nur der Nicht-variable Teil ohne Datum persistiert werden und YGOR vervollständigt diese: https://www.emeraldgrouppublishing.com/sites/default/files/2020-09/EmeraldPublishing_Global_EmeraldAccountingFinanceandEconomicseJournalCollection_

Zur Fehlervermeidung sollte die GOKb bei der Eingabe der URL diese prüfen und entsprechend beschneiden.

Korrespondierendes YGOR-Ticket: https://github.com/hbz/laser-ygor/issues/295

**Comment by VolkerHBZ** [comment]
Wenn man die Anbieter nicht dazu bringen kann, ihre **aktuellen** Daten unter **einer** URL zu veröffentlichen, dann wäre die einfachste Lösung, in die persistierte URL Platzhalter einzufügen, die einen Format-String enthalten, der direkt in SimpleDateFormat gefüttert werden kann. 
z.B. https://www.emeraldgrouppublishing.com/sites/default/files/{yyyy-MM}/EmeraldPublishing_Global_EmeraldAccountingFinanceandEconomicseJournalCollection_{yyy-MM-dd}.txt

Einen festen Link auf das neueste KBART-File zu haben, wäre die sichere Lösung, die ich unter allen anderen Möglichkeiten bevorzugen würde. 

Andererseits spart es immens Rechenzeit und Serverlast, wenn an 300 Tagen im Jahr **keine** Daten zu verarbeiten sind, weil die Datei nur einmal pro Woche neu erstellt wird und an den anderen Tagen eine 404 zurück kommt. Falls der Anbieter das URL-Schema auch nur marginal verändert (z.B. .tsv statt .txt) bleibt diese Änderung auf HBZ-Seite jedoch unbemerkt, bis es jemanden stört, wenn Daten in der GOKb nicht aktuell sind. Dazu müsste allerdings eine Person mit Detailkenntnissen über das Angebot eines Providers die Daten durchkämmen - wer macht das schon? Täglich.

**Comment by darupp** [comment]
Da die URL schon in https://github.com/openlibraryenvironment/gokb/issues/327 persistiert wird und auch Platzhalter akzeptiert werden, ist dieses Ticket als erledigt zu betrachten.
