### ISSUE TITLE
TIPP - Name reaktivieren

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#340]
# Problem
KBART Records haben ein Namensfeld _publication_title_. Beim Import in die GOKb wird dieser Titel oft nur als _Variant Name_ zur `TitleInstance` hinzugefügt. Hier kann es sein, dass

- Der Haupttitel der `TitleInstance` nicht vollständig ist, weil er u.U. aus verschiedenen Feldern der ZDB zusammengesetzt werden muss (z.B. _Physical Review A_ bzw. _B_ ist nur als _Physical Review_ angelegt worden).
- Bei einem falsch zugeordneten Haupttitel der Name ggf. überhaupt nicht mehr stimmt. 

Daher ist es wichtig, den _publication_title_ am entsprechenden `TIPP` zu bewahren.

# Details
- Implementierung bzw. Reaktivierung des _Name_-Feldes des TIPPs (wird von `KBComponent` geerbt)
- Setzen des TIPP-Namens beim Einspielen/Updaten eines TIPPs per Schnittstelle. Die bisherige Funktion (ggf. Setzen als _Variant Name_  der `TitleInstance`) bleibt dabei bestehen.
- Darstellung in der Oberfläche
  - In der `Package`-View in Schritt 4 (_Titel im Paket_) in der Spalte _Details_ anstelle des jetzigen Namens aus der `TitleInstance`
  - Im entsprechenden Detail-Modal oberhalb von Allgemein als zentrale Information dieses Paket-Titels darstellen
- Nutzung des `TIPP`-Namens beim Export als KBART-Datei unter _publication_title_
- Ausgabe über der Package-APIs (OAI etc.) sollte zusätzlich zum `TitleInstance`-Namen den `TIPP`-Namen anbieten
- Grundsätzlich sollten alle diese Funktionen, die neu auf den `TIPP`-Namen zurückgreifen statt auf den `TitleInstance`-Namen, als Fallback den entsprechenden `TitleInstance`-Namen nehmen.

**Comment by darupp** [comment]
Bezüglich der Integration Package API wird der Name nur innerhalb eines `title`-Objekts innerhalb des `TIPP`-Objekts weitergegeben. Es wäre stringenter, den _publication_title_ als `name` zusätztlich direkt im `TIPP`-Objekt anzugeben. So ist auch eine deutliche Differenzierung zweier Namensformen möglich, bei der die eine aus dem KBART-Feld _publication_title_ kommt, die andere aus einer Schnittstelle.

Hierzu ist eine YGOR-seitige Änderung notwendig. Korrespondierendes YGOR-Ticket: https://github.com/hbz/laser-ygor/issues/307

# Bisheriges JSON
```
{
    "coverage" : [ {
      "coverageDepth" : "Fulltext",
      "startDate" : "2007-01-01",
      "startIssue" : "1",
      "startVolume" : "1"
    } ],
    "title" : {
      "identifiers" : [ {
        "value" : "2567-6334",
        "type" : "eissn"
      }, {
        "value" : "1865-1739",
        "type" : "issn"
      } ],
      "name" : "Adipositas - Ursachen, Folgeerkrankungen, Therapie",
      "type" : "serial"
    },
    "platform" : {
      "name" : "NatHosting",
      "primaryUrl" : "https://www.nathosting.de/"
    },
    "url" : "https://doi.org/10.1055/s-00034923"
  }
```

**Comment by philboeselager** [comment]
Eine alternative Namensform zum `tipp.title.name` kann natürlich eingeführt werden, allerdings sollte die Bezeichnung auch (ent-) sprechend sein. Also bspw. als Objekt: 

    "name" : {
        "source" : "kbart",
        "value" : "Adipositas - Ursachen, Folgeerkrankungen, Therapie"
    }

Macht es denn überhaupt Sinn, die Namen in den Paketen abweichend zum Titel vorzuhalten? In der realen Welt nicht, oder?

**Comment by VolkerHBZ** [comment]
wenn das aus KBComponent geerbte Property 'name' benutzt werden soll, dann ist das nur ein einzelner String, ohne die Möglichkeit, dem _Namen_ eine Source zuordnen zu können. Das geht nur auf KBComponent-Ebene, also neben dem Namen.
Der Sinn besteht m.E. darin, paketspezifisch abgeänderte Namen eines Titels nachvollziehen zu können. Offenbar fehlt den vorhandenen Alternative Names diese Möglichkeit der Zuordnung.

**Comment by darupp** [comment]
Ich würde ebenfalls in Hinblick auf die GOKb-Struktur `name` verwenden. `tipp.name` dürfte ja sauber zu unterscheiden sein von `tipp.title.name`. Andere Name-Properties in der GOKb, die von `KBComponent` (wie der Plattformname) sind ja auch schon so im JSON benannt, also z.B. `tipp.platform.name`
