### ISSUE TITLE
Export not containing values for ebooks

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#35]
Tested on dev & QA
With reference to LAS:eR-tickets [ERMS-1203](https://jira.hbz-nrw.de/browse/ERMS-1203) and [ERMS-1150](https://jira.hbz-nrw.de/browse/ERMS-1150)

When exporting EBook-packages (KBart and GOKb), no identifiers are being exported.
Tested with:
- dev: https://phaeton-dev.hbz-nrw.de/gokb/public/packageContent/org.gokb.cred.Package%3A812354
- qa: https://phaeton-qa.hbz-nrw.de/gokb/public/packageContent/org.gokb.cred.Package%3A812408

**Comment by darupp** [comment]
This refers to the .tsv export on package level. Additionally, other monograph fields (as defined in KBART Phase II) are not exported either as a quick check shows.

**Comment by hornmo** [comment]
This looks like a duplicate to #22

**Comment by darupp** [comment]
Yes, I'm closing this one
