### ISSUE TITLE
LastRun nur bei "Erfolg" setzen

### ISSUE THREAD

**Issue by philboeselager** [openlibraryenvironment/gokb#369]
Das Feld `lastRun` einer Source sollte vermutlich nur dann verändert werden, wenn sichergestellt ist, dass das betreffende Update auch erfolgreich war.

Das Kriterium für "Erfolg" wäre dabei wohl am besten von GOKb-Entwicklern (mit) zu bestimmen.

**Comment by VolkerHBZ** [comment]
Aktuell wird lastRun gesetzt, wenn die kommunikation zwischen GOKb und Ygor erfolgreich war und in dem Thread keine Exceptions geflogen sind. Eine Abfrage, die das Ergebnis des xrPackage-Jobs erfmittelt, kann ich da noch mit dran bauen, sofern das irgendwo verfügbar ist. Allerdings hast du Recht: wir müssen wahrscheinlich erstmal definieren, an welcher Grenze aus einem ziemlich guten ein erfolgreiches Update wird.
