### ISSUE TITLE
Neuer Endpunkt resourceSync

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#380]
Für eine deutlich performantere Synchronisation nehmender Systeme wäre ein Endpunkt wünschenswert, der folgendermaßen aussieht (Methode bulkRecords): https://github.com/hbz/lobid-resources/blob/f93201bec043cc732b27814a6ab4aea390d1aa9e/web/app/controllers/resources/Application.java

Der neue Endpunkt soll (mindestens) folgende Parameter verarbeiten:
- componentType
- changedSince
- offset (optional)
- max (optional)
- status (optional)

offset/max sind deshalb optional, weil das Staffeln der Ergebnismenge implizit durch die gebende Stelle übernommen wird.

**Comment by croqueGrec09** [comment]
Aus dem Fehlerstacktrace, als ich über die 10000er-Marke wollte: Failed to execute phase [query], all shards failed; shardFailures {[BggQpTcCS9-bKV-SP9xMdQ][gokbg3][0]: RemoteTransportException[[BggQpTc][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Result window is too large, from + size must be less than or equal to: [10000] but was [11000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.]; }
Da wird schon die Scroll-Api vorgeschlagen. Vielleicht hilft euch das auch weiter.

**Comment by philboeselager** [comment]
@croqueGrec09 Der Scroll-Endpunkt steht unter dem Endpunkt 

    api/scroll?component_type=BookInstance
    
zur Verfügung. Alle scroll-Requests returnieren eine `scrollId`, die bei den Requests 2 bis n jeweils als Parameter einzureichen ist. Dabei ist jeweils die zuletzt returnierte scrollId zu übergeben, d. h. jede scrollId funktioniert genau 1x, nämlich für die Folgeseite des letzten Requests.

Die Größe der Scrolls ist zur Zeit fix auf 5000 Records eingestellt. Wir können testen, ob andere Größen eine bessere Performanz bieten, falls unzureichend.

Wird eine Antwort der Größe 0 bis 4999 vom Endpunkt zurück gegeben, hat die Scroll-Suche ihr Ende erreicht, und das anfragende System sollte keine weiteren Requests für diese Suche erzeugen.

Bitte testen und mich bei Fragen gerne direkt ansprechen.

**Comment by philboeselager** [comment]
@croqueGrec09 Hier noch ein Beispiel-Schnipsel zur Verwendung der Schnittstelle:

    String url = "http://yourGokbInstanceGoesHere/api/scroll?component_type=JournalInstance"
    boolean scrollOn = true
    String scrollId = null
    while (scrollOn){
      String scrollUrl = url + "&scrollId=${scrollId}"
      def http = (scrollId == null) ? new HTTPBuilder(url) : new HTTPBuilder(scrollUrl)
      http.request(Method.POST, ContentType.JSON) { request ->
        response.success = { response, resultMap ->
          if (resultMap.size < resultMap.scrollSize){
            scrollOn = false
          }
          else{
            scrollId = resultMap.scrollId
          }
          // do something with the data chunks received in resultMap.records
          // ...
        }
      }
    }

**Comment by croqueGrec09** [comment]
Sooo ... nach meinem Urlaub habe ich mich alsbald an das Testen gemacht und dabei direkt einen sehr doofen Bug entdeckt: der Parameter changedSince wird augenscheinlich nicht verarbeitet. Ich bekomme mit changedSince=2020-11-02 00:00:00 die gleiche Ergebnismenge, wie mit changedSince=2021-01-11 00:00:00 und zwar Ergebnisse, die lastUpdated auf April '20 (!) gesetzt haben ...

**Comment by philboeselager** [comment]
@croqueGrec09 Zu den optionalen Parametern:

- `offset` wird in Scroll-Requests nicht unterstützt und macht auch nicht Sinn, da der Elasticsearch-Mechanismus ohne einen solchen Parameter funktioniert.
- `max` könnte implementiert werden. Die Bedeutung wäre dann die maximale Größe eines Teilergebnisses (einer "Seite"). Hier sollten allerdings nicht zu große Werte erlaubt werden, da diese wiederum den Arbeitsspeicher stärker beanspruchen würden. Im Sinne einer kontinuierlichen Prozessierung mit verteilten Lasten ist der Wert nicht zu groß zu wählen. Mein Vorschlag wäre, den Parameter erst einmal bei 5000 fix zu lassen.
- `status` wäre hier auch nur bedingt sinnvoll, da die Antwort innerhalb weniger Sekunden zurück kommt. Ich würde vorschlagen, diesen Parameter weg zu lassen. (Oder ich verstehe den Sinn noch nicht.)

**Comment by croqueGrec09** [comment]
Zu offset und max gebe ich Recht. Waren auch nur deshalb notwendig, um bei der Synchronisation eine Paginierung zu erwirken, was anderweitig und implizit schon umgesetzt ist.
Status wäre deshalb sinnvoll, um explizit nur aktive oder nur erwartete Titel/Pakete/etc. zu erhalten. Dieser Filter ist in manchen nehmenden Systemen recht häufig im Einsatz.
