### ISSUE TITLE
Feedback zu nicht eingespielten Titeln / TIPPs

### ISSUE THREAD

**Issue by philboeselager** [openlibraryenvironment/gokb#383]
Im Zusammenhang eines Ygor-Tickets (siehe https://github.com/hbz/laser-ygor/issues/280#issuecomment-688179358) entstand der Verbesserungs-Vorschlag, bei der Einspielung abgelehnte TIPPs in einem Kommentar-Feld des Pakets aufzulisten, um dem Nutzer eine bessere Transparenz zu bieten.

Da es in diesem Zusammenhang offensichtlich Ygor-seitig nichts mehr zu tun gibt, und das Ticket etwas in Vergessenheit geraten zu scheint, überführe ich die Idee in dieses neue GOKb-Ticket.

**Comment by VolkerHBZ** [comment]
Das Ergebnis des Imports kann nach Abschluß des Imports in der JSON-Antwort ausgelesen werden, die Ygor regelmäßig erfragt. Während der Import abgearbeitet wird, ist der aktuelle Stand fehlerhafter Datensätze unter Manage Jobs in der GUI abzulesen. Ein Kommentarfeld, welches alle NICHT-importierten TIPPs aufzählt, erscheint mir pradox und kann schnell unübersichtlich werden, wenn Pakete viele Fehler produzieren.

**Comment by philboeselager** [comment]
Das Problem der potentiellen Unübersichtlichkeit ist in jedem Fall gegeben, egal ob Kommentarfeld, Ygor oder GOKb-Jobs. Das Hinterlegen der Information im Paket hat folgende Vorteile:

- bessere Zuordbarkeit (gegenüber Job-Liste)
- Persistierung (gegenüber Ygor-Ergebnis-Anzeige) für spätere Bearbeitung

**Comment by darupp** [comment]
Eine entsprechende Umsetzung ist auf jeden Fall notwendig, um für den Nutzer eine Transparenz zu bieten. Philipps Argumente finde ich überzeugend. Mittelfristig kann man sich überlegen, ob wir hierfür nicht sogar eine eigene Struktur schaffen (sozusagen ein eigenes Kommentarfeld), aber zunächst ist das sehr sinnvoll.

**Comment by VolkerHBZ** [comment]
Für die Kommunikation des Systems mit dem Anwender gibt es bereits das Instrument des ReviewRequests (z.B. https://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.Package%3A13273627#review ), welches bereits benutzt wird, um Nachrichten aus dem Import an den Nutzer weiterzuleiten. Seid ihr sicher, dass ihr noch einen komplett neuen Kanal für Nachrichen aufmachen wollt?

**Comment by philboeselager** [comment]
> Für die Kommunikation des Systems mit dem Anwender gibt es bereits das Instrument des ReviewRequests (z.B. https://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.Package%3A13273627#review ), welches bereits benutzt wird, um Nachrichten aus dem Import an den Nutzer weiterzuleiten. Seid ihr sicher, dass ihr noch einen komplett neuen Kanal für Nachrichen aufmachen wollt?

Eine Link-Liste zu den verbundenen Review-Requests wäre aus meiner Sicht optimal.

**Comment by darupp** [comment]
Ja, tatsächlich hat @VolkerHBZ recht. Wir haben eine Struktur und sollten auch kein Provisiorium machen. Tatsächlich ist ein Review Request ebenfalls der beste Weg. Hier ergibt sich nur das Problem, dass ein Review Request zwingend mit einer `KBComponent` verknüpft ist - und ein nicht eingespielter Titel eben keine KBComponent darstellt. 

Aber tatsächlich könnte man das entsprechend so gestalten: 
  - Ein neuer Review Request wird einfgeführt mit dem Typ "KBART Record not imported" oder ähnlich-
  - Die verknüpfte KBComponent ist das entsprechende Package. 
  - Die entsprechende Info enthält die Liste, welche Records nicht eingespielt wurden (Idealerweise mit Titel und Identifikatoren)

Dazu muss auf jeden Fall eine Übersicht der dem Paket (oder den Paket-Tipps) zugeordneten RRs gegeben sein. Das ist in der alten Oberfläche gegeben, in der neuen fehlt es noch bzw. ist auf einer allgemeinen RR-Seite, nicht beim Paket.

**Comment by VolkerHBZ** [comment]
natürlich ist die verknüpfte Komponente das Package - was auch sonst?
Die Übersicht der dem Package zugehörigen RRs ist - oh: Wunder! - auf dem Tab ReviewRequests in der Package View zu finden. Man muß nur mal nach unten scrollen. Die Fehlermeldung kommt dann mehr oder weniger straight aus dem Fehlerobjekt, was auch an Ygor geht.

**Comment by darupp** [comment]
> Das ist in der alten Oberfläche gegeben, in der neuen fehlt es noch bzw. ist auf einer allgemeinen RR-Seite, nicht beim Paket.

**Comment by philboeselager** [comment]
> natürlich ist die verknüpfte Komponente das Package - was auch sonst?
> Die Übersicht der dem Package zugehörigen RRs ist - oh: Wunder! - auf dem Tab ReviewRequests in der Package View zu finden. Man muß nur mal nach unten scrollen. Die Fehlermeldung kommt dann mehr oder weniger straight aus dem Fehlerobjekt, was auch an Ygor geht.

Das ist ja prima. Dann hat es da anscheinend nur an entsprechender Information gefehlt.
@MiriKon : ist die Übersicht über die verknüpften ReviewRequests auf der Paket-Ansicht, die auch nicht eingespielte TIPPs betreffen, hinreichend, um zu wissen, welche TIPPs fehlen?
Möglicherweise könnte man in dieser Ansicht noch einen Filter einbauen, falls sich die ReviewRequests in ihrem Inhalt stark unterscheiden und das zu Verwirrung führt.
