### ISSUE TITLE
Limit on provider search results display when creating packages

### ISSUE THREAD

**Issue by hemmefelix** [openlibraryenvironment/gokb#386]
The provider reference list in the new GOKb UI is limited to 10 entries when creating a new package. Therefore a user cannot select certain providers, e.g. "Springer" (GOKb org-id 85324), from the list to link it to the package. As a workaround I tried a lookup with the org id, but that failed.

The max number of results displayed to the user should be increased.

![image](https://user-images.githubusercontent.com/17432725/103776999-8da53980-5030-11eb-880d-03d3a6ea6f66.png)

**Comment by hornmo** [comment]
Searching by component ID will be fixed going forward, which will probably be more comfortable. Adding more results specifically for orgs would be an issue for https://github.com/openlibraryenvironment/gokb-ui

**Comment by hemmefelix** [comment]
Hey @hornmo , do you want me to file an issue on the https://github.com/openlibraryenvironment/gokb-ui repo to address the number of results displayed?

**Comment by hornmo** [comment]
Yeah, that would be great!
