### ISSUE TITLE
Enhancement: Search package titles by identifier

### ISSUE THREAD

**Issue by hemmefelix** [openlibraryenvironment/gokb#395]
From package view it is only possible to search contained e-resources by title as phrase search, not keyword search. Example:

Package: [Edward Elgar:Edward Elgar E-Book Archive in Business & Management, Economics and Finance:Nationallizenz](https://gokb.org/gokb-ui/#/package/9355221)

The user wants to know if the following title is included in this package (from package view w/o additional search from title search screen):
[The Handbook of Globalisation, Third Edition](https://gokb.org/gokb-ui/#/title/6626549)

A search on `handbook globalisation` results in 0 hits, because the search is phrase only. Search on identifier should be supported in order to find e-resources in packages by id. Most important identifier seems (e)ISBN and (e)ISSN.

User story: As a GOKb data manager I want to check if a certain title is included in the package I'm currently investigating. A search by resource title brings up 0 search results.

**Comment by hemmefelix** [comment]
Shall I file an issue on the https://github.com/openlibraryenvironment/gokb-ui repo instead?

**Comment by hornmo** [comment]
As of v8.14.0, entering an identifier value should work. Switching to tokenized search instead of phrase search would require some additional effort and testing (and should probably get its own ticket in gokb-ui).
