### ISSUE TITLE
Add KBART monograph fields to Class BookInstance

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#4]
For inserting EBooks into the GOKb via KBART files, additional attributes have to be implemented on BookInstance level (or possibly higher, i.e. TitleInstance level):

first_author: string
first_editor: string

Though there is a data structure for adding people to a KBComponent (I think this is for authors or editors, although there are no bootstrapped roles), KBART data is not sufficient to identify people correctly, so that the data structure for people cannot be used properly. Instead of creating people objects with insufficient data, we could use the new attributes without further parsing or matching in the way they are used in KBART.

**Comment by hornmo** [comment]
Added String fields to BookInstance in 9042f85c61f584af00048fea2859c1d465c208d5.
