### ISSUE TITLE
Inserting monograph specific KBART fields via crossreferencing API

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#5]
On title level, monograph specific KBART data has to be processed via the crossreferencing API (title):

date_monograph_published_print --> BookInstance.dateFirstInPrint
date_monograph_published_online --> BookInstance.dateFirstOnline

monograph_volume --> BookInstance.volumeNumber
monograph_edition --> [May be parsed to fill BookInstance.editionNumber, editionDifferentiator and editionStatement]

first_editor --> [new attribute, see #4 ]
first_author --> [new attribute, see #4 ]

It hast yet to be decided how to handle the fields: 

parent_publication_title_id 
preceding_publication_title_id

**Comment by hornmo** [comment]
CrossReferenceTitle will already process the BookInstance String fields 
* `editionNumber`
* `editionDifferentiator`
* `editionStatement`
* `volumeNumber`
* `summaryOfContent`
as well as the dates in `dateFirstInPrint` and `dateFirstOnline`

As of release 8.0.12 (83d9d2f276dc5c605ace80d8faa78c17a82f5512), BookInstance has new String fields `firstAuthor` and `firstEditor`. These are not yet considered by crossReferenceTitle though.

_preceding_publication_title_id_ should be converted to proper history events for importing them via crossreferencing API.

There is currently no concept for parent publications in GOKb.

**Comment by darupp** [comment]
1) As KBART files don't differentiate between those three internal edition fields, we have to decide where the processing of the KBART field *monograph_edition* into `editionNumber`, `editionDifferentiator` or `editionStatement` should be done. Should *monograph_edition* be given to the API additional to the three implemented fields so that it can be processed internally? Or should the API strictly accept only those three internal fields and let an external import client process *monograph_edition*? I'd prefer an (optional) internal processing.

2) At the moment I don't know how the processing should work and how these fields are used. In the following function the `editionDifferentiator` is considered similar to what I would expect from `editionNumber`, as it is concatenated after 'ed.' in the bookDiscriminator:
https://github.com/openlibraryenvironment/gokb/blob/83d9d2f276dc5c605ace80d8faa78c17a82f5512/server/gokbg3/grails-app/domain/org/gokb/cred/BookInstance.groovy#L98-L108

From my understanding, a usable purpose of these fields could be:
  * `editionStatement` - The whole unprocessed statement as it is given in *monograph_edition* like "3rd revised and expanded edition"
  * `editionNumber` - The parsed (integer) value of the above like "3" so that i.e. different editions could be put in order automatically. 
  * `editionDifferentiator` - Like above, but with keeping in mind that the discrimination of different entries work on this field and therefore it could be that it has to left intentionally blank or that more than a number has to be added if a logical differentiation is needed or not.

3) On *preceding_publication_title_id* I think the same, although the date for this history event lacks. 

4) On *parent_publication_title_id* - there is a domain class Work.groovy that groups different titleInstances under a single KBComponent, but I don't find a use or a counterpart in the user interface. Maybe this was considered for a parent title concept?
https://github.com/openlibraryenvironment/gokb/blob/83d9d2f276dc5c605ace80d8faa78c17a82f5512/server/gokbg3/grails-app/domain/org/gokb/cred/Work.groovy#L1-L21

**Comment by croqueGrec09** [comment]
I would like to push this issue and suggest that bk_edition_number is going to be set to integer in order to prevent a priori erroneous values. Already now, we have a few (~3) false values in gokb.org. We should fix this ASAP in order to prevent larger cleanup later.

**Comment by hornmo** [comment]
Added in #224
