### ISSUE TITLE
Internal Server Error on "Ensure UUIDs"

### ISSUE THREAD

**Issue by philboeselager** [openlibraryenvironment/gokb#58]
Trying to run "Ensure UUIDs" created an `Error 500: Internal Server Error`:

	URI: /gokb/admin/jobs
	Class: groovy.lang.MissingMethodException
	Message: groovy.lang.MissingMethodException: No signature of method: org.gokb.CleanupService$__tt__ensureUuids_closure13$_closure22.doCall() is applicable for argument types: (java.lang.Long, java.lang.Integer) values: [41606, 0] Possible solutions: doCall(java.lang.Object), findAll(), findAll()
	Caused by: No signature of method: org.gokb.CleanupService$__tt__ensureUuids_closure13$_closure22.doCall() is applicable for argument types: (java.lang.Long, java.lang.Integer) values: [41606, 0] Possible solutions: doCall(java.lang.Object), findAll(), findAll()

Trace:

		Line | Method
	->>  122 | report           in java.util.concurrent.FutureTask
	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
	|    192 | get              in     ''
	|     53 | get . . . . . .  in org.grails.async.factory.future.FutureTaskPromise
	|    171 | get              in com.k_int.ConcurrencyManagerService$Job
	|    283 | doCall . . . . . in org.gokb.AdminController$_jobs_closure11
	|    279 | jobs             in org.gokb.AdminController
	|    223 | invoke . . . . . in org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker
	|    188 | invoke           in org.grails.core.DefaultGrailsControllerClass
	|     90 | handle . . . . . in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
	|    967 | doDispatch       in org.springframework.web.servlet.DispatcherServlet
	|    901 | doService . . .  in     ''
	|    970 | processRequest   in org.springframework.web.servlet.FrameworkServlet
	|    861 | doGet . . . . .  in     ''
	|    846 | service          in     ''
	|     55 | doFilterInternal in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
	|    317 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
	|    127 | invoke . . . . . in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
	|     91 | doFilter         in     ''
	|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
	|    114 | doFilter         in org.springframework.security.web.access.ExceptionTranslationFilter
	|     64 | doFilter . . . . in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
	|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
	|     54 | doFilter . . . . in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
	|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
	|    158 | doFilter . . . . in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
	|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
	|    170 | doFilter . . . . in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
	|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
	|    200 | doFilter . . . . in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
	|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
	|     64 | doFilter . . . . in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
	|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
	|    105 | doFilter . . . . in org.springframework.security.web.context.SecurityContextPersistenceFilter
	|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
	|     58 | doFilter . . . . in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
	|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
	|    214 | doFilterInternal in org.springframework.security.web.FilterChainProxy
	|    177 | doFilter         in     ''
	|     77 | doFilterInternal in org.grails.web.servlet.mvc.GrailsWebRequestFilter
	|     67 | doFilterInternal in org.grails.web.filters.HiddenHttpMethodFilter
	|    130 | doFilter . . . . in org.springframework.boot.web.support.ErrorPageFilter
	|     66 | access$000       in     ''
	|    105 | doFilterInternal in org.springframework.boot.web.support.ErrorPageFilter$1
	|    123 | doFilter         in org.springframework.boot.web.support.ErrorPageFilter
	|   1142 | runWorker . . .  in java.util.concurrent.ThreadPoolExecutor
	|    617 | run              in java.util.concurrent.ThreadPoolExecutor$Worker
	^    745 | run . . . . . .  in java.lang.Thread

	Caused by MissingMethodException: No signature of method: org.gokb.CleanupService$__tt__ensureUuids_closure13$_closure22.doCall() is applicable for argument types: (java.lang.Long, java.lang.Integer) values: [41606, 0]
	Possible solutions: doCall(java.lang.Object), findAll(), findAll()
	->>  247 | doCall           in org.gokb.CleanupService$__tt__ensureUuids_closure13
	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
	|    153 | doInHibernate    in org.grails.orm.hibernate.GrailsHibernateTemplate$1
	|    299 | doExecute . . .  in org.grails.orm.hibernate.GrailsHibernateTemplate
	|    243 | execute          in     ''
	|    150 | executeWithNewSession in     ''
	|    360 | withNewSession   in org.grails.orm.hibernate.AbstractHibernateDatastore
	|     60 | withNewSession . in org.grails.orm.hibernate.AbstractHibernateGormStaticApi
	|   1025 | withNewSession   in org.grails.datastore.gorm.GormEntity$Trait$Helper
	|    246 | $tt__ensureUuids in org.gokb.CleanupService
	|     94 | doInTransaction  in grails.gorm.transactions.GrailsTransactionTemplate$2
	|    133 | execute . . . .  in org.springframework.transaction.support.TransactionTemplate
	|     91 | execute          in grails.gorm.transactions.GrailsTransactionTemplate
	|    143 | doCall . . . . . in org.gokb.AdminController$_ensureUuids_closure3
	|    266 | run              in java.util.concurrent.FutureTask
	|   1142 | runWorker . . .  in java.util.concurrent.ThreadPoolExecutor
	|    617 | run              in java.util.concurrent.ThreadPoolExecutor$Worker
	^    745 | run . . . . . .  in java.lang.Thread

GOKb v. 8.1.0
phaeton-qa

**Comment by hornmo** [comment]
Fixed in v8.3.1 (5851448).
