### ISSUE TITLE
New Curatory Group does not show up in Dropdown

### ISSUE THREAD

**Issue by philboeselager** [openlibraryenvironment/gokb#59]
I can't assign [this new curatory group](https://phaeton-qa.hbz-nrw.de/gokb/resource/show/org.gokb.cred.CuratoryGroup%3A994085) created by Miriam to [this user](https://phaeton-qa.hbz-nrw.de/gokb/resource/show/org.gokb.cred.User%3A994079). The CG does not show up in the Dropdown for CG selection on the user's page - whereas other older CGs do show up.

GOKb v. 8.1.0
phaeton-qa

**Comment by darupp** [comment]
Done. I think the problem was that you have to type the first letter to change the selected items as the Dropdown only shows only maximal 10 random entries.

**Comment by philboeselager** [comment]
I see. This will probably occur as a question by users because the page limit is not that visible. It would help to sort entries alphabetically here as this might tell that the list is longer than the visible entries only.

**Comment by darupp** [comment]
I absolutely agree. This is one of the many problems with the UI. But I wouldn't invest time and energy in the current UI unless it is absolutely necessary.
