### ISSUE TITLE
Unify Elasticsearch configuration

### ISSUE THREAD

**Issue by philboeselager** [openlibraryenvironment/gokb#6]
Setting up GOKb locally, I realized it used different Elasticsearch configuration for reading and writing. While the writing destination index was defined in [application.yml | environments | development | gokb | es | index](https://github.com/openlibraryenvironment/gokb/blob/g3_master/server/gokbg3/grails-app/conf/application.yml#L142) as `gokbg3dev`, the quering configuration was defined elsewhere as `gokbg3`.

**Comment by VolkerHBZ** [comment]
Es scheint, als würde der org.gokb.GlobalSearchController in Zeile 46 die Konfiguration grailsApplication.config.globalSearch.indices nicht finden, weil sie nicht existiert und darum den Fallback "gokbg3" verwenden. Ich habe das lokal schonmal angepasst, aber bevor ich das einchecke, sollte da jemand drüber schauen, der sich damit auskennt...

Grundsätzlich stellt sich mir allerdings die Frage, ob es sinnvoll ist, einen hardcoded Default zu benutzen: ist die Konfiguration erstmal aus dem application.yml rausgefallen, wird es schwer bzw. ohne exakte Dokumentation unmöglich, den korrekten Key wiederherzustellen, mit dem man den Default überschreiben kann. Sinnvoller scheint mir ein Fail-Fast-Ansatz, der einfach knallt, wenn die Konfiguration nicht zum aktuellen System passt. Dann kann ein Benutzer evtl. auch selbständig durch lesen der Konfigurationsfiles die Applikation an seine Bedürfnisse anpassen.

**Comment by VolkerHBZ** [comment]
@hornmo das wäre mein Vorschlag, das Problem zu lösen... https://github.com/openlibraryenvironment/gokb/pull/24/files

**Comment by hornmo** [comment]
PR https://github.com/openlibraryenvironment/gokb/pull/24 has been merged
