### ISSUE TITLE
Bootstrap predefinitions for user roles

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#60]
At the Moment, after a new GOKb installation you have to edit the rights manually. This should be done in the Bootstrap.groovy according to this template: https://docs.google.com/document/d/1wxvLuwmaZyXwlE-SDO6JRHQ2hnLMosiZGykFmdMODUo/edit#heading=h.tfwkt66ewl10

**Comment by hornmo** [comment]
Added in #78
