### ISSUE TITLE
Data Manager Tool: Multiple platform entries

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#61]
As data managing tool, we need a view for multiple platform entries. 

*Navigation:* As menue item under "Admin"

This should be a list view like /gokb/search/index?qbe=g%3A1platforms, but with multiple platforms (different platforms with same name and/or same Primary URL).

**Comment by philboeselager** [comment]
@darupp Ist das noch aktuell? Wenn ja, bitte erläutern, sonst bitte schließen.

**Comment by darupp** [comment]
Nicht mehr aktuell. Geschlossen.
