### ISSUE TITLE
Messaging deleted packages for harvesting systems

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#66]
Harvesting systems via OAI-PMH don't know at the moment whether a package has simple not changed or has been deleted.

Different possible solutions:

- Is there a OAI-PMH specification addressing this problem? Then we have to implement it
- Using the ES-Index for getting the status "deleted" for certain GUIDs.

**Comment by croqueGrec09** [comment]
The OAI PMH spectification states in its guidelines, section 2.5.1 of the general document: 

If a record is no longer available then it is said to be deleted. Repositories must declare one of three levels of support for deleted records in the deletedRecord element of the [Identify](http://www.openarchives.org/OAI/openarchivesprotocol.html#Identify) response:

- no - the repository does not maintain information about deletions. A repository that indicates this level of support must not reveal a deleted status in any response.
- persistent - the repository maintains information about deletions with no time limit. A repository that indicates this level of support must persistently keep track of the full history of deletions and consistently reveal the status of a deleted record over time.
- transient - the repository does not guarantee that a list of deletions is maintained persistently or consistently. A repository that indicates this level of support may reveal a deleted status for records.

If a repository does not keep track of deletions then such records will simply vanish from responses and there will be no way for a harvester to discover deletions through continued incremental harvesting. If a repository does keep track of deletions then the datestamp of the deleted record must be the date and time that it was deleted. Responses to [GetRecord](http://www.openarchives.org/OAI/openarchivesprotocol.html#GetRecord) request for a deleted record must then include a [header](http://www.openarchives.org/OAI/openarchivesprotocol.html#header) with the attribute status="deleted", and must not include metadata or about parts. Similarly, responses to [selective harvesting](http://www.openarchives.org/OAI/openarchivesprotocol.html#SelectiveHarvesting) requests with set membership and date range criteria that include deleted records must include the headers of these records. Incremental harvesting will thus discover deletions from repositories that keep track of them.

Deleted status is a property of individual records. Like a normal record, a deleted record is identified by a [unique identifier](http://www.openarchives.org/OAI/openarchivesprotocol.html#UniqueIdentifier), a [metadataPrefix](http://www.openarchives.org/OAI/openarchivesprotocol.html#metadataPrefix) and a [datestamp](http://www.openarchives.org/OAI/openarchivesprotocol.html#Datestamp). Other records, with different metadataPrefix but the same unique identifier, may remain available for the item.

(http://www.openarchives.org/OAI/openarchivesprotocol.html#DeletedRecords)

**Comment by hornmo** [comment]
As of right now, GOKb does mark deleted records via the header status attribute. Since this was added relatively recently and to avoid problems with existing harvesting operations (of LAS:eR for example), the metadata is still supplied on top of this.

**Comment by croqueGrec09** [comment]
The OAI PMH request delivers deleted packages. Can thus be closed.
