### ISSUE TITLE
Data Management Tool - Set titles without packages to "Rejected"

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#67]
We need a new admin function to get rid of wrong titles. It should be found menue under the "admin" akkordeon and only with role "Admin":

New function to get all titles that 

  * have no package tipps (see "package availability" tab in title view

AND

  * have no history events

The titles should be set to "status:deleted", so that we can expunge them with the admin function "Expunge deleted records"

**Comment by VolkerHBZ** [comment]
Feature implemented in Version 8.3.5
