### ISSUE TITLE
OAI PMH interface is not delivering providedPlatforms

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#75]
Discovered and documented as LAS:eR-issue ERMS-1573:

Comparing these two records:
https://phaeton.hbz-nrw.de/gokb/oai/packages?verb=getRecord&metadataPrefix=gokb&identifier=b2e9d143-1721-4a8a-a048-0723b6d425d7

with

https://phaeton.hbz-nrw.de/gokb/resource/show/b2e9d143-1721-4a8a-a048-0723b6d425d7

The LAS:eR-sync would expect a tag providedPlatforms which is inexistent, so no package - provider connection is being established even if there is one.

**Comment by hornmo** [comment]
Fixed in #82
