### ISSUE TITLE
Import via CrossReferencing API: Package referencing failed with exception!

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#76]
See attached files. A Package Import via YGOR or ~~Curl~~ RESTer-Plugin is rejected without proper information of the reason.

Happened on phaeton-qa. 
[tandf.zip](https://github.com/openlibraryenvironment/gokb/files/3477594/tandf.zip)

```
{
    "results": [],
    "result": "ERROR",
    "message": "Package referencing failed with exception!",
    "errors": []
}
```
What happened? And could the API answer be enhanced to return better information?

**Comment by croqueGrec09** [comment]
This message is also displayed when at the last step, I wish to send package to GOKb and enter my GOKb credentials.

**Comment by darupp** [comment]
I shortened the list to only one TIPP and it worked - seems to be either a problem of specific tipps or a problem regarding the size of the file.

**Comment by VolkerHBZ** [comment]
https://phaeton-qa.hbz-nrw.de/gokb/admin/jobs shows the first appearance of a "Package referencing failed with exception!" on Aug 6, 13:53:50 

Maybe, it actually IS connected to the not-so-unique record in the database that the ES updater is complaining about every five minutes since 2019-05-08 13:59:24.877

**Comment by darupp** [comment]
Problem still occurs. Tested on phaeton-qa with Annual Review package:

  * Only one current platform with the given url "http://www.annualreview.org/" exists
  * Accepting tipps is somewhat erratic. Even with the response "Package referencing failed" sometimes a single tipps exists.
  * It seems to be caused by the coverage dates. After deleting the Array below it worked nicely.

 ```
 "coverage" : [ {
      "coverageDepth" : "fulltext",
      "startDate" : "2009-01-01 00:00:00.000",
      "coverageNote" : "Not sold separately, must be purchased as part of the 3-journal Economics Collection; site license required.",
      "startVolume" : "1"
    } ],
 ```
Further investigation: 
This works:
```
       "coverage": [{
            "coverageDepth": "Fulltext",
            "startIssue": "",
            "endVolume": "",
            "endDate": "",
            "startVolume": "",
            "coverageNote": "",
            "embargo": "",
            "endIssue": "",
            "startDate": "1997-01-01 00:00:00.000"
         }],
```
This doesn't work:
```
    "coverage" : [ {
      "coverageDepth" : "Fulltext",
      "startDate" : "1997-01-01 00:00:00.000"
    } ],
```
After some testing it is clear that it depends of the fields "endDate" and "startDate". When these fields are not given both, the package referencing doesn't work. 

@VolkerHBZ This has to be addressed via YGOR. The whole set of coverage fields have to be implemented in the Ygor JSON. 
@hornmo Is ist possible to make the gokb integration controller less strict regarding empty fields? Can we get additionally more detailed error responses from the api?


[https://app.zenhub.com/files/103426961/7dc72351-4199-4e91-9192-2110bd902b5b/download](https://app.zenhub.com/files/103426961/7dc72351-4199-4e91-9192-2110bd902b5b/download)

**Comment by darupp** [comment]
After some tests this error message seems to be a generic error message when something goes awry via the package API. In the following example the reason was a title doublette:

```
{
    "results": [],
    "result": "ERROR",
    "message": "Package referencing failed with exception!",
    "errors": [
        {
            "code": 500,
            "message": "There was an exception while trying to referencing the Package",
            "data": {
                "nominalProvider": "Annual Reviews, Inc.",
                "listVerifiedDate": "",
                "userListVerifier": "",
                "nominalPlatform": {
                    "name": "Annual Reviews",
                    "primaryUrl": "http://www.annualreviews.org/"
                },
                "listStatus": "Checked",
                "global": "Consortium",
                "consistent": "Yes",
                "source": {},
                "listVerifier": "",
                "paymentType": "",
                "curatoryGroups": [
                    "LAS:eR",
                    "hbz"
                ],
                "scope": "",
                "name": "AnnualReviews TestPaket NL",
                "variantNames": [],
                "fixed": "Yes",
                "additionalProperties": [],
                "breakable": "No"
            }
        }
    ]
}
```

At the moment, package import via the API is not possible even in small quantities. A single tipp error in a >500 titles package leads to this unspecified error message with no chance to identify the problematic title. We absolutely have to improve the API error messages:

  * Specify the concrete tipps that are problematic
  * Specify the concrete cause of error (i.e. title doublette, wrong coverage dates etc.) as error type
  * Provide an non-technical explanation of the error message type including an howto for the next steps
  * Provide, if possible, a direct link to the problematic objects

**Comment by VolkerHBZ** [comment]
I have introduced some minor changes with the (big) effect that a single title validation error does not break the whole package import without any specific message due to a NullPointerException, but gives an error message text, that is actually stating the name of the invalid title.
