### ISSUE TITLE
KBART export not containing column zdb_id

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#8]
With reference to ticket [ERMS-933](https://jira.hbz-nrw.de/browse/ERMS-933) of LAS:eR

To preselect values in the issue entitlement selection for a subscription based upon a KBART file, I need to match against different identifiers. Currently, a KBART export coming from GOKb does not contain any ZDB IDs which actually should be the first ID against which I should match.

I thus need the column zdb_id in the KBART file containing the ZDB identifier.

**Comment by darupp** [comment]
Although zdb_id is not KBART standard, I absolutely recommend the export as it is a primary identifier for Journals.

**Comment by darupp** [comment]
Alternative solution: A third export aside from "KBART" and "GOKb .tsv" like "KBART with all Identifiers" where all additional identifiers will be given in an extra column.

Problems to solve:
  *  title_id will be mapped via import to certain namespaces and won't be mapped back to title_id.
  * Import of title_id is at the moment not clear if this is a TIPP or an Title identifier. If it's a TIPP identfier, you would have for each different package the same IDs.
  * how should the namespaces be translated to KBART column headers? Same as namespace name or from an extra namespace attribute for a KBART conform column header?

**Comment by philboeselager** [comment]
Please specify the Definition Of Done and assign back to me then, @darupp .

**Comment by darupp** [comment]
After a webcon with @hornmo it beacme clear that we first have to solve some conceptual problems in an upcoming monday webcon. I put this issue on hold.

**Comment by hornmo** [comment]
Column `zdb_id` added to exports in d4d2d3e
